/** updated by adriac */
/* GroupUpdated.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from GroupUpdated.vala, do not modify */

/*[Adriac:Entitas.Event::GroupUpdated:EntitasEventGroupUpdated:entitas_event_group_updated]*/
/*[Adriac:Entitas.Event:GroupUpdated:Listener:EntitasEventGroupUpdatedListener:entitas_event_group_updated_listener]*/
/* ******************************************************************************
 *# MIT License
 *
 * Copyright (c) 2015-2017 Bruce Davidson &lt;darkoverlordofdata@gmail.com&gt;
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * 'Software'), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <SDL_rect.h>

typedef struct _EntitasEventGroupUpdated EntitasEventGroupUpdated;
typedef struct _EntitasEventGroupUpdatedListener EntitasEventGroupUpdatedListener;
typedef struct _EntitasGroup EntitasGroup;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_TRANSFORM (entitas_transform_get_type ())

#define SDX_MATH_TYPE_VECTOR2 (sdx_math_vector2_get_type ())
typedef struct _SdxMathVector2 SdxMathVector2;
typedef struct _SdxGraphicsSprite SdxGraphicsSprite;
typedef struct _EntitasTransform EntitasTransform;
typedef struct _EntitasEventEntityChanged EntitasEventEntityChanged;
typedef struct _EntitasEventEntityReleased EntitasEventEntityReleased;
typedef struct _EntitasEventComponentReplaced EntitasEventComponentReplaced;

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _EntitasBackground EntitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _EntitasBullet EntitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _EntitasEnemy1 EntitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _EntitasEnemy2 EntitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _EntitasEnemy3 EntitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _EntitasExpires EntitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _EntitasHealth EntitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _EntitasHud EntitasHud;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _EntitasLayer EntitasLayer;

#define ENTITAS_TYPE_PLAYER (entitas_player_get_type ())
typedef struct _EntitasPlayer EntitasPlayer;

#define ENTITAS_TYPE_SHOW (entitas_show_get_type ())
typedef struct _EntitasShow EntitasShow;

#define ENTITAS_TYPE_SOUND (entitas_sound_get_type ())
typedef struct _SdxAudioSound SdxAudioSound;
typedef struct _EntitasSound EntitasSound;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef SdxGraphicsSprite SdxGraphicsSpriteTextSprite;
typedef struct _EntitasText EntitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _EntitasTint EntitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _EntitasTween EntitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _EntitasVelocity EntitasVelocity;
typedef struct _EntitasEntity EntitasEntity;
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
// symtbl.1 entitas_group
void entitas_group_release (EntitasGroup* self);
void entitas_group_free (EntitasGroup* self);
EntitasGroup* entitas_group_retain (EntitasGroup* self);
#define _entitas_group_release0(var) ((var == NULL) ? NULL : (var = (entitas_group_release (var), NULL)))
typedef struct _Block6Data Block6Data;
// symtbl.1 entitas_event_group_updated
void entitas_event_group_updated_release (EntitasEventGroupUpdated* self);
void entitas_event_group_updated_free (EntitasEventGroupUpdated* self);
EntitasEventGroupUpdated* entitas_event_group_updated_retain (EntitasEventGroupUpdated* self);
#define _entitas_event_group_updated_release0(var) ((var == NULL) ? NULL : (var = (entitas_event_group_updated_release (var), NULL)))

struct _SdxMathVector2 {
	gfloat x;
	gfloat y;
};

struct _EntitasTransform {
	SdxMathVector2* scale;
	SdxMathVector2* position;
	SDL_Rect* aabb;
	SdxGraphicsSprite* sprite;
};

struct _EntitasBackground {
	gboolean active;
};

struct _EntitasBullet {
	gboolean active;
};

struct _EntitasEnemy1 {
	gboolean active;
};

struct _EntitasEnemy2 {
	gboolean active;
};

struct _EntitasEnemy3 {
	gboolean active;
};

struct _EntitasExpires {
	gfloat value;
};

struct _EntitasHealth {
	gfloat current;
	gfloat maximum;
};

struct _EntitasHud {
	gboolean active;
};

struct _EntitasLayer {
	gint value;
};

struct _EntitasPlayer {
	gboolean active;
};

struct _EntitasShow {
	gboolean active;
};

struct _EntitasSound {
	SdxAudioSound* sound;
};

struct _EntitasText {
	gchar* text;
	SdxGraphicsSpriteTextSprite* sprite;
};

struct _EntitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _EntitasTween {
	gfloat min;
	gfloat max;
	gfloat speed;
	gboolean repeat;
	gboolean active;
};

struct _EntitasVelocity {
	gfloat x;
	gfloat y;
};

struct _EntitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	EntitasTransform transform;
	EntitasEventEntityChanged* onComponentAdded;
	EntitasEventEntityChanged* onComponentRemoved;
	EntitasEventEntityReleased* onEntityReleased;
	EntitasEventComponentReplaced* onComponentReplaced;
	EntitasBackground* background;
	EntitasBullet* bullet;
	EntitasEnemy1* enemy1;
	EntitasEnemy2* enemy2;
	EntitasEnemy3* enemy3;
	EntitasExpires* expires;
	EntitasHealth* health;
	EntitasHud* hud;
	EntitasLayer* layer;
	EntitasPlayer* player;
	EntitasShow* show;
	EntitasSound* sound;
	EntitasText* text;
	EntitasTint* tint;
	EntitasTween* tween;
	EntitasVelocity* velocity;
};

typedef void (*EntitasEventGroupUpdatedHandler) (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated, void* user_data);
struct _EntitasEventGroupUpdated {
	gint ref_count;
	GPtrArray* listeners;
	EntitasEventGroupUpdatedHandler Dispatch;
	gpointer Dispatch_target;
	GDestroyNotify Dispatch_target_destroy_notify;
};

struct _Block6Data {
	int _ref_count_;
	EntitasEventGroupUpdated* self;
	EntitasGroup* g;
	EntitasEntity* e;
	gint index;
	void* component;
	void* updated;
};

struct _EntitasEventGroupUpdatedListener {
	gint ref_count;
	EntitasEventGroupUpdatedHandler event;
	gpointer event_target;
	GDestroyNotify event_target_destroy_notify;
};



void entitas_event_group_updated_free (EntitasEventGroupUpdated * self);
void entitas_event_group_updated_listener_free (EntitasEventGroupUpdatedListener * self);
void entitas_group_free (EntitasGroup * self);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_transform_get_type (void) G_GNUC_CONST;
GType sdx_math_vector2_get_type (void) G_GNUC_CONST;
SdxMathVector2* sdx_math_vector2_dup (const SdxMathVector2* self);
void sdx_math_vector2_free (SdxMathVector2* self);
void sdx_graphics_sprite_free (SdxGraphicsSprite * self);
EntitasTransform* entitas_transform_dup (const EntitasTransform* self);
void entitas_transform_free (EntitasTransform* self);
void entitas_transform_copy (const EntitasTransform* self, EntitasTransform* dest);
void entitas_transform_destroy (EntitasTransform* self);
void entitas_event_entity_changed_free (EntitasEventEntityChanged * self);
void entitas_event_entity_released_free (EntitasEventEntityReleased * self);
void entitas_event_component_replaced_free (EntitasEventComponentReplaced * self);
GType entitas_background_get_type (void) G_GNUC_CONST;
EntitasBackground* entitas_background_dup (const EntitasBackground* self);
void entitas_background_free (EntitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
EntitasBullet* entitas_bullet_dup (const EntitasBullet* self);
void entitas_bullet_free (EntitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
EntitasEnemy1* entitas_enemy1_dup (const EntitasEnemy1* self);
void entitas_enemy1_free (EntitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
EntitasEnemy2* entitas_enemy2_dup (const EntitasEnemy2* self);
void entitas_enemy2_free (EntitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
EntitasEnemy3* entitas_enemy3_dup (const EntitasEnemy3* self);
void entitas_enemy3_free (EntitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
EntitasExpires* entitas_expires_dup (const EntitasExpires* self);
void entitas_expires_free (EntitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
EntitasHealth* entitas_health_dup (const EntitasHealth* self);
void entitas_health_free (EntitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
EntitasHud* entitas_hud_dup (const EntitasHud* self);
void entitas_hud_free (EntitasHud* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
EntitasLayer* entitas_layer_dup (const EntitasLayer* self);
void entitas_layer_free (EntitasLayer* self);
GType entitas_player_get_type (void) G_GNUC_CONST;
EntitasPlayer* entitas_player_dup (const EntitasPlayer* self);
void entitas_player_free (EntitasPlayer* self);
GType entitas_show_get_type (void) G_GNUC_CONST;
EntitasShow* entitas_show_dup (const EntitasShow* self);
void entitas_show_free (EntitasShow* self);
GType entitas_sound_get_type (void) G_GNUC_CONST;
void sdx_audio_sound_free (SdxAudioSound * self);
EntitasSound* entitas_sound_dup (const EntitasSound* self);
void entitas_sound_free (EntitasSound* self);
void entitas_sound_copy (const EntitasSound* self, EntitasSound* dest);
void entitas_sound_destroy (EntitasSound* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
EntitasText* entitas_text_dup (const EntitasText* self);
void entitas_text_free (EntitasText* self);
void entitas_text_copy (const EntitasText* self, EntitasText* dest);
void entitas_text_destroy (EntitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
EntitasTint* entitas_tint_dup (const EntitasTint* self);
void entitas_tint_free (EntitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
EntitasTween* entitas_tween_dup (const EntitasTween* self);
void entitas_tween_free (EntitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
EntitasVelocity* entitas_velocity_dup (const EntitasVelocity* self);
void entitas_velocity_free (EntitasVelocity* self);
EntitasEntity* entitas_entity_dup (const EntitasEntity* self);
void entitas_entity_free (EntitasEntity* self);
void entitas_entity_copy (const EntitasEntity* self, EntitasEntity* dest);
void entitas_entity_destroy (EntitasEntity* self);
static void entitas_event_group_updated_instance_init (EntitasEventGroupUpdated * self);
static void _entitas_event_group_updated_dispatch_lambda18_ (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated);
static void __entitas_event_group_updated_dispatch_lambda18__entitas_event_group_updated_handler (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated, gpointer self);
EntitasEventGroupUpdated* entitas_event_group_updated_retain (EntitasEventGroupUpdated* self);
void entitas_event_group_updated_release (EntitasEventGroupUpdated* self);
void entitas_event_group_updated_free (EntitasEventGroupUpdated* self);
EntitasEventGroupUpdated* entitas_event_group_updated_new (void);
// symtbl.2 entitas_event_group_updated_listener
void entitas_event_group_updated_listener_release (EntitasEventGroupUpdatedListener* self);
void entitas_event_group_updated_listener_free (EntitasEventGroupUpdatedListener* self);
EntitasEventGroupUpdatedListener* entitas_event_group_updated_listener_retain (EntitasEventGroupUpdatedListener* self);
static void _entitas_event_group_updated_listener_release0_ (gpointer var);
static void __lambda19_ (EntitasEventGroupUpdated* self, EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated);
static Block6Data* block6_data_ref (Block6Data* _data6_);
static void block6_data_unref (void * _userdata_);
static void __lambda20_ (Block6Data* _data6_, EntitasEventGroupUpdatedListener* listener);
static void ___lambda20__gfunc (gconstpointer data, gpointer self);
static void ___lambda19__entitas_event_group_updated_handler (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated, gpointer self);
void entitas_event_group_updated_Add (EntitasEventGroupUpdated* self, EntitasEventGroupUpdatedHandler event, void* event_target);
EntitasEventGroupUpdatedListener* entitas_event_group_updated_listener_new (EntitasEventGroupUpdatedHandler event, void* event_target);
void entitas_event_group_updated_Remove (EntitasEventGroupUpdated* self, EntitasEventGroupUpdatedHandler event, void* event_target);
void entitas_event_group_updated_Clear (EntitasEventGroupUpdated* self);
static void entitas_event_group_updated_listener_instance_init (EntitasEventGroupUpdatedListener * self);
EntitasEventGroupUpdatedListener* entitas_event_group_updated_listener_retain (EntitasEventGroupUpdatedListener* self);
void entitas_event_group_updated_listener_release (EntitasEventGroupUpdatedListener* self);
void entitas_event_group_updated_listener_free (EntitasEventGroupUpdatedListener* self);


static void _entitas_event_group_updated_dispatch_lambda18_ (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated) {
	g_return_if_fail (g != NULL);
}


static void __entitas_event_group_updated_dispatch_lambda18__entitas_event_group_updated_handler (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated, gpointer self) {
	_entitas_event_group_updated_dispatch_lambda18_ (g, e, index, component, updated);
}


EntitasEventGroupUpdated* entitas_event_group_updated_retain (EntitasEventGroupUpdated* self) {
	EntitasEventGroupUpdated* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void entitas_event_group_updated_release (EntitasEventGroupUpdated* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		entitas_event_group_updated_free (self);
	}
}


// symtbl.2 entitas_event_group_updated_listener
void entitas_event_group_updated_listener_release (EntitasEventGroupUpdatedListener* self);
void entitas_event_group_updated_listener_free (EntitasEventGroupUpdatedListener* self);
EntitasEventGroupUpdatedListener* entitas_event_group_updated_listener_retain (EntitasEventGroupUpdatedListener* self);
static void _entitas_event_group_updated_listener_release0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (entitas_event_group_updated_listener_release (var), NULL));
}


static gpointer _entitas_group_retain0 (gpointer self) {
	return self ? entitas_group_retain (self) : NULL;
}


static Block6Data* block6_data_ref (Block6Data* _data6_) {
	g_atomic_int_inc (&_data6_->_ref_count_);
	return _data6_;
}


static void block6_data_unref (void * _userdata_) {
	Block6Data* _data6_;
	_data6_ = (Block6Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data6_->_ref_count_)) {
		EntitasEventGroupUpdated* self;
		self = _data6_->self;
		_entitas_group_release0 (_data6_->g);
		_entitas_event_group_updated_release0 (self);
		g_slice_free (Block6Data, _data6_);
	}
}


static void __lambda20_ (Block6Data* _data6_, EntitasEventGroupUpdatedListener* listener) {
	EntitasEventGroupUpdated* self;
	EntitasEventGroupUpdatedListener* _tmp0_;
	EntitasEventGroupUpdatedHandler _tmp1_;
	void* _tmp1__target;
	EntitasGroup* _tmp2_;
	EntitasEntity* _tmp3_;
	gint _tmp4_;
	void* _tmp5_;
	void* _tmp6_;
	self = _data6_->self;
	g_return_if_fail (listener != NULL);
	_tmp0_ = listener;
	_tmp1_ = _tmp0_->event;
	_tmp1__target = _tmp0_->event_target;
	_tmp2_ = _data6_->g;
	_tmp3_ = _data6_->e;
	_tmp4_ = _data6_->index;
	_tmp5_ = _data6_->component;
	_tmp6_ = _data6_->updated;
	_tmp1_ (_tmp2_, _tmp3_, _tmp4_, _tmp5_, _tmp6_, _tmp1__target);
}


static void ___lambda20__gfunc (gconstpointer data, gpointer self) {
	__lambda20_ (self, (EntitasEventGroupUpdatedListener*) data);
}


static void __lambda19_ (EntitasEventGroupUpdated* self, EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated) {
	Block6Data* _data6_;
	EntitasGroup* _tmp0_;
	EntitasGroup* _tmp1_;
	EntitasEntity* _tmp2_;
	gint _tmp3_;
	void* _tmp4_;
	void* _tmp5_;
	GPtrArray* _tmp6_;
	g_return_if_fail (g != NULL);
	_data6_ = g_slice_new0 (Block6Data);
	_data6_->_ref_count_ = 1;
	_data6_->self = entitas_event_group_updated_retain (self);
	_tmp0_ = g;
	_tmp1_ = _entitas_group_retain0 (_tmp0_);
	_entitas_group_release0 (_data6_->g);
	_data6_->g = _tmp1_;
	_tmp2_ = e;
	_data6_->e = _tmp2_;
	_tmp3_ = index;
	_data6_->index = _tmp3_;
	_tmp4_ = component;
	_data6_->component = _tmp4_;
	_tmp5_ = updated;
	_data6_->updated = _tmp5_;
	_tmp6_ = self->listeners;
	g_ptr_array_foreach (_tmp6_, ___lambda20__gfunc, _data6_);
	block6_data_unref (_data6_);
	_data6_ = NULL;
}


static void ___lambda19__entitas_event_group_updated_handler (EntitasGroup* g, EntitasEntity* e, gint index, void* component, void* updated, gpointer self) {
	__lambda19_ ((EntitasEventGroupUpdated*) self, g, e, index, component, updated);
}


EntitasEventGroupUpdated* entitas_event_group_updated_new (void) {
	EntitasEventGroupUpdated* self;
	GPtrArray* _tmp0_;
	self = g_slice_new0 (EntitasEventGroupUpdated);
	entitas_event_group_updated_instance_init (self);
	_tmp0_ = g_ptr_array_new_full ((guint) 0, _entitas_event_group_updated_listener_release0_);
	_g_ptr_array_unref0 (self->listeners);
	self->listeners = _tmp0_;
	(self->Dispatch_target_destroy_notify == NULL) ? NULL : (self->Dispatch_target_destroy_notify (self->Dispatch_target), NULL);
	self->Dispatch = NULL;
	self->Dispatch_target = NULL;
	self->Dispatch_target_destroy_notify = NULL;
	self->Dispatch = ___lambda19__entitas_event_group_updated_handler;
	self->Dispatch_target = entitas_event_group_updated_retain (self);
	self->Dispatch_target_destroy_notify = entitas_event_group_updated_release;
	return self;
}


void entitas_event_group_updated_Add (EntitasEventGroupUpdated* self, EntitasEventGroupUpdatedHandler event, void* event_target) {
	GPtrArray* _tmp0_;
	EntitasEventGroupUpdatedHandler _tmp1_;
	void* _tmp1__target;
	EntitasEventGroupUpdatedListener* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->listeners;
	_tmp1_ = event;
	_tmp1__target = event_target;
	_tmp2_ = entitas_event_group_updated_listener_new (_tmp1_, _tmp1__target);
	g_ptr_array_add (_tmp0_, _tmp2_);
}


static gint g_ptr_array_get_length (GPtrArray* self) {
	gint result;
	guint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->len;
	result = (gint) _tmp0_;
	return result;
}


static void g_ptr_array_set_length (GPtrArray* self, gint value) {
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	g_ptr_array_set_size (self, _tmp0_);
}


void entitas_event_group_updated_Remove (EntitasEventGroupUpdated* self, EntitasEventGroupUpdatedHandler event, void* event_target) {
	g_return_if_fail (self != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_;
				GPtrArray* _tmp3_;
				gint _tmp4_;
				gint _tmp5_;
				GPtrArray* _tmp6_;
				gint _tmp7_;
				gconstpointer _tmp8_;
				EntitasEventGroupUpdatedHandler _tmp9_;
				void* _tmp9__target;
				EntitasEventGroupUpdatedHandler _tmp10_;
				void* _tmp10__target;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = self->listeners;
				_tmp4_ = g_ptr_array_get_length (_tmp3_);
				_tmp5_ = _tmp4_;
				if (!(_tmp2_ < _tmp5_)) {
					break;
				}
				_tmp6_ = self->listeners;
				_tmp7_ = i;
				_tmp8_ = g_ptr_array_index (_tmp6_, (guint) _tmp7_);
				_tmp9_ = ((EntitasEventGroupUpdatedListener*) _tmp8_)->event;
				_tmp9__target = ((EntitasEventGroupUpdatedListener*) _tmp8_)->event_target;
				_tmp10_ = event;
				_tmp10__target = event_target;
				if (_tmp9_ == _tmp10_) {
					GPtrArray* _tmp11_;
					gint _tmp12_;
					_tmp11_ = self->listeners;
					_tmp12_ = i;
					g_ptr_array_remove_index_fast (_tmp11_, (guint) _tmp12_);
					return;
				}
			}
		}
	}
}


void entitas_event_group_updated_Clear (EntitasEventGroupUpdated* self) {
	GPtrArray* _tmp0_;
	GPtrArray* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->listeners;
	_tmp1_ = self->listeners;
	_tmp2_ = g_ptr_array_get_length (_tmp1_);
	_tmp3_ = _tmp2_;
	g_ptr_array_remove_range (_tmp0_, (guint) 0, (guint) _tmp3_);
}


EntitasEventGroupUpdatedListener* entitas_event_group_updated_listener_retain (EntitasEventGroupUpdatedListener* self) {
	EntitasEventGroupUpdatedListener* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void entitas_event_group_updated_listener_release (EntitasEventGroupUpdatedListener* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		entitas_event_group_updated_listener_free (self);
	}
}


EntitasEventGroupUpdatedListener* entitas_event_group_updated_listener_new (EntitasEventGroupUpdatedHandler event, void* event_target) {
	EntitasEventGroupUpdatedListener* self;
	EntitasEventGroupUpdatedHandler _tmp0_;
	void* _tmp0__target;
	self = g_slice_new0 (EntitasEventGroupUpdatedListener);
	entitas_event_group_updated_listener_instance_init (self);
	_tmp0_ = event;
	_tmp0__target = event_target;
	(self->event_target_destroy_notify == NULL) ? NULL : (self->event_target_destroy_notify (self->event_target), NULL);
	self->event = NULL;
	self->event_target = NULL;
	self->event_target_destroy_notify = NULL;
	self->event = _tmp0_;
	self->event_target = _tmp0__target;
	self->event_target_destroy_notify = NULL;
	return self;
}


static void entitas_event_group_updated_listener_instance_init (EntitasEventGroupUpdatedListener * self) {
	self->ref_count = 1;
}


void entitas_event_group_updated_listener_free (EntitasEventGroupUpdatedListener * self) {
	(self->event_target_destroy_notify == NULL) ? NULL : (self->event_target_destroy_notify (self->event_target), NULL);
	self->event = NULL;
	self->event_target = NULL;
	self->event_target_destroy_notify = NULL;
	g_slice_free (EntitasEventGroupUpdatedListener, self);
}


static void entitas_event_group_updated_instance_init (EntitasEventGroupUpdated * self) {
	self->ref_count = 1;
	self->Dispatch = __entitas_event_group_updated_dispatch_lambda18__entitas_event_group_updated_handler;
	self->Dispatch_target = self;
	self->Dispatch_target_destroy_notify = NULL;
}


void entitas_event_group_updated_free (EntitasEventGroupUpdated * self) {
	_g_ptr_array_unref0 (self->listeners);
	(self->Dispatch_target_destroy_notify == NULL) ? NULL : (self->Dispatch_target_destroy_notify (self->Dispatch_target), NULL);
	self->Dispatch = NULL;
	self->Dispatch_target = NULL;
	self->Dispatch_target_destroy_notify = NULL;
	g_slice_free (EntitasEventGroupUpdated, self);
}




