/** updated by adriac */
/* api.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from api.gs, do not modify */

/*//[Adriac:Sdx::JsGame:SdxJsGame:sdx_js_game]*/

#include <glib.h>
#include <glib-object.h>








