/** updated by adriac */
/* NinePatch.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from NinePatch.vala, do not modify */

/*[Adriac:Sdx.Graphics::NinePatch:SdxGraphicsNinePatch:sdx_graphics_nine_patch]*/
/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <SDL_rect.h>
#include <SDL_render.h>
#include <SDL_pixels.h>
#include <stdlib.h>
#include <string.h>

typedef struct _SdxGraphicsNinePatch SdxGraphicsNinePatch;
typedef struct _SdxGraphicsSurface SdxGraphicsSurface;
typedef SdxGraphicsSurface SdxGraphicsSurfaceTextureSurface;

#define SDX_GRAPHICS_TYPE_BLIT (sdx_graphics_blit_get_type ())
typedef struct _SdxGraphicsBlit SdxGraphicsBlit;
// symtbl.1 sdx_graphics_surface
void sdx_graphics_surface_release (SdxGraphicsSurface* self);
void sdx_graphics_surface_free (SdxGraphicsSurface* self);
SdxGraphicsSurface* sdx_graphics_surface_retain (SdxGraphicsSurface* self);
#define _sdx_graphics_surface_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_surface_release (var), NULL)))
typedef struct _SdxGraphicsTextureRegion SdxGraphicsTextureRegion;
typedef SdxGraphicsTextureRegion SdxGraphicsTextureRegionFromRegion;
// symtbl.1 sdx_graphics_texture_region
void sdx_graphics_texture_region_release (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
SdxGraphicsTextureRegion* sdx_graphics_texture_region_retain (SdxGraphicsTextureRegion* self);
#define _sdx_graphics_texture_region_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_texture_region_release (var), NULL)))

struct _SdxGraphicsBlit {
	SDL_Rect source;
	SDL_Rect dest;
	SDL_RendererFlip flip;
};

struct _SdxGraphicsNinePatch {
	gint ref_count;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint bottomLeft;
	gint bottomCenter;
	gint bottomRight;
	gint middleLeft;
	gint middleCenter;
	gint middleRight;
	gint topLeft;
	gint topCenter;
	gint topRight;
	gint top;
	gint left;
	gint right;
	gint bottom;
	gfloat leftWidth;
	gfloat rightWidth;
	gfloat middleWidth;
	gfloat middleHeight;
	gfloat topHeight;
	gfloat bottomHeight;
	SdxGraphicsBlit slice[9];
	gint idx;
	SDL_Color color;
	gfloat padLeft;
	gfloat padRight;
	gfloat padTop;
	gfloat padBottom;
	gint sourceTop;
	gint sourceLeft;
};

struct _SdxGraphicsTextureRegion {
	gint ref_count;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint top;
	gint left;
	gint width;
	gint height;
	gint regionWidth;
	gint regionHeight;
	gfloat u;
	gfloat v;
	gfloat u2;
	gfloat v2;
	gint index;
	gchar* name;
	gint offsetX;
	gint offsetY;
	gint packedWidth;
	gint packedHeight;
	gint originalWidth;
	gint originalHeight;
	gboolean rotate;
	gint* splits;
	gint splits_length1;
	gint* pads;
	gint pads_length1;
};

typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_UnableToLoadSurface,
	SDX_SDL_EXCEPTION_UnableToLoadTexture,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement,
	SDX_SDL_EXCEPTION_IllegalStateException,
	SDX_SDL_EXCEPTION_IllegalArgumentException,
	SDX_SDL_EXCEPTION_RuntimeException,
	SDX_SDL_EXCEPTION_NotReached
} SdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()


void sdx_graphics_nine_patch_free (SdxGraphicsNinePatch * self);
void sdx_graphics_surface_free (SdxGraphicsSurface * self);
GType sdx_graphics_blit_get_type (void) G_GNUC_CONST;
SdxGraphicsBlit* sdx_graphics_blit_dup (const SdxGraphicsBlit* self);
void sdx_graphics_blit_free (SdxGraphicsBlit* self);
static void sdx_graphics_nine_patch_instance_init (SdxGraphicsNinePatch * self);
#define SDX_GRAPHICS_NINE_PATCH_TOP_LEFT 0
#define SDX_GRAPHICS_NINE_PATCH_TOP_CENTER 1
#define SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT 2
#define SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT 3
#define SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER 4
#define SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT 5
#define SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT 6
#define SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER 7
#define SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT 8
SdxGraphicsNinePatch* sdx_graphics_nine_patch_retain (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_release (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_free (SdxGraphicsNinePatch* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion * self);
SdxGraphicsNinePatch* sdx_graphics_nine_patch_new (SdxGraphicsTextureRegion* region, gint left, gint right, gint top, gint bottom);
GQuark sdx_sdl_exception_quark (void);
gint sdx_graphics_texture_region_GetRegionWidth (SdxGraphicsTextureRegion* self);
gint sdx_graphics_texture_region_GetRegionHeight (SdxGraphicsTextureRegion* self);
SdxGraphicsTextureRegionFromRegion* sdx_graphics_texture_region_from_region_new (SdxGraphicsTextureRegion* region, gint x, gint y, gint width, gint height);
void sdx_graphics_nine_patch_Load (SdxGraphicsNinePatch* self, SdxGraphicsTextureRegion** patches, int patches_length1);
gint sdx_graphics_nine_patch_Add (SdxGraphicsNinePatch* self, SdxGraphicsTextureRegion* region, SDL_Color color, gboolean isStretchW, gboolean isStretchH);
gint sdx_graphics_surface_get_width (SdxGraphicsSurface* self);
gint sdx_graphics_surface_get_height (SdxGraphicsSurface* self);
void sdx_graphics_nine_patch_SetColor (SdxGraphicsNinePatch* self, SDL_Color color);
SDL_Color sdx_graphics_nine_patch_GetColor (SdxGraphicsNinePatch* self);
gfloat sdx_graphics_nine_patch_GetLeftWidth (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetLeftWidth (SdxGraphicsNinePatch* self, gfloat leftWidth);
gfloat sdx_graphics_nine_patch_GetRightWidth (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetRightWidth (SdxGraphicsNinePatch* self, gfloat rightWidth);
gfloat sdx_graphics_nine_patch_GetTopHeight (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetTopHeight (SdxGraphicsNinePatch* self, gfloat topHeight);
gfloat sdx_graphics_nine_patch_GetBottomHeight (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetBottomHeight (SdxGraphicsNinePatch* self, gfloat bottomHeight);
gfloat sdx_graphics_nine_patch_GetMiddleWidth (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetMiddleWidth (SdxGraphicsNinePatch* self, gfloat middleWidth);
gfloat sdx_graphics_nine_patch_GetMiddleHeight (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetMiddleHeight (SdxGraphicsNinePatch* self, gfloat middleHeight);
gfloat sdx_graphics_nine_patch_GetTotalWidth (SdxGraphicsNinePatch* self);
gfloat sdx_graphics_nine_patch_GetTotalHeight (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetPadding (SdxGraphicsNinePatch* self, gfloat left, gfloat right, gfloat top, gfloat bottom);
gfloat sdx_graphics_nine_patch_GetPadLeft (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetPadLeft (SdxGraphicsNinePatch* self, gfloat left);
gfloat sdx_graphics_nine_patch_GetPadRight (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetPadRight (SdxGraphicsNinePatch* self, gfloat right);
gfloat sdx_graphics_nine_patch_GetPadTop (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetPadTop (SdxGraphicsNinePatch* self, gfloat top);
gfloat sdx_graphics_nine_patch_GetPadBottom (SdxGraphicsNinePatch* self);
void sdx_graphics_nine_patch_SetPadBottom (SdxGraphicsNinePatch* self, gfloat bottom);
void sdx_graphics_nine_patch_Scale (SdxGraphicsNinePatch* self, gfloat scaleX, gfloat scaleY);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

extern const SDL_Color SDX_COLOR_White;

SdxGraphicsNinePatch* sdx_graphics_nine_patch_retain (SdxGraphicsNinePatch* self) {
	SdxGraphicsNinePatch* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_nine_patch_release (SdxGraphicsNinePatch* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_nine_patch_free (self);
	}
}


static gpointer _sdx_graphics_texture_region_retain0 (gpointer self) {
	return self ? sdx_graphics_texture_region_retain (self) : NULL;
}


SdxGraphicsNinePatch* sdx_graphics_nine_patch_new (SdxGraphicsTextureRegion* region, gint left, gint right, gint top, gint bottom) {
	SdxGraphicsNinePatch* self;
	SdxGraphicsTextureRegion* _tmp0_;
	gint _tmp1_;
	SdxGraphicsTextureRegion* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	SdxGraphicsTextureRegion* _tmp8_;
	gint middleWidth = 0;
	SdxGraphicsTextureRegion* _tmp10_;
	gint _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	gint middleHeight = 0;
	SdxGraphicsTextureRegion* _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	gint _tmp17_;
	SdxGraphicsTextureRegion** patches = NULL;
	SdxGraphicsTextureRegion** _tmp18_;
	gint patches_length1;
	gint _patches_size_;
	gint _tmp19_;
	gint _tmp44_;
	gint _tmp72_;
	gboolean _tmp103_ = FALSE;
	gint _tmp104_;
	gboolean _tmp127_ = FALSE;
	gint _tmp128_;
	SdxGraphicsTextureRegion** _tmp151_;
	gint _tmp151__length1;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (region != NULL, NULL);
	self = g_slice_new0 (SdxGraphicsNinePatch);
	sdx_graphics_nine_patch_instance_init (self);
	self->idx = 0;
	_tmp0_ = region;
	_tmp1_ = _tmp0_->top;
	self->sourceTop = _tmp1_;
	_tmp2_ = region;
	_tmp3_ = _tmp2_->left;
	self->sourceLeft = _tmp3_;
	_tmp4_ = top;
	self->top = _tmp4_;
	_tmp5_ = left;
	self->left = _tmp5_;
	_tmp6_ = right;
	self->right = _tmp6_;
	_tmp7_ = bottom;
	self->bottom = _tmp7_;
	_tmp8_ = region;
	if (_tmp8_ == NULL) {
		GError* _tmp9_;
		_tmp9_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_IllegalArgumentException, "region cannot be null.");
		_inner_error_ = _tmp9_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp10_ = region;
	_tmp11_ = sdx_graphics_texture_region_GetRegionWidth (_tmp10_);
	_tmp12_ = left;
	_tmp13_ = right;
	middleWidth = (_tmp11_ - _tmp12_) - _tmp13_;
	_tmp14_ = region;
	_tmp15_ = sdx_graphics_texture_region_GetRegionHeight (_tmp14_);
	_tmp16_ = top;
	_tmp17_ = bottom;
	middleHeight = (_tmp15_ - _tmp16_) - _tmp17_;
	_tmp18_ = g_new0 (SdxGraphicsTextureRegion*, 9 + 1);
	patches = _tmp18_;
	patches_length1 = 9;
	_patches_size_ = patches_length1;
	_tmp19_ = top;
	if (_tmp19_ > 0) {
		gint _tmp20_;
		gint _tmp27_;
		gint _tmp35_;
		_tmp20_ = left;
		if (_tmp20_ > 0) {
			SdxGraphicsTextureRegion** _tmp21_;
			gint _tmp21__length1;
			SdxGraphicsTextureRegion* _tmp22_;
			gint _tmp23_;
			gint _tmp24_;
			SdxGraphicsTextureRegionFromRegion* _tmp25_;
			SdxGraphicsTextureRegion* _tmp26_;
			_tmp21_ = patches;
			_tmp21__length1 = patches_length1;
			_tmp22_ = region;
			_tmp23_ = left;
			_tmp24_ = top;
			_tmp25_ = sdx_graphics_texture_region_from_region_new (_tmp22_, 0, 0, _tmp23_, _tmp24_);
			_sdx_graphics_texture_region_release0 (_tmp21_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT]);
			_tmp21_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT] = (SdxGraphicsTextureRegion*) _tmp25_;
			_tmp26_ = _tmp21_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT];
		}
		_tmp27_ = middleWidth;
		if (_tmp27_ > 0) {
			SdxGraphicsTextureRegion** _tmp28_;
			gint _tmp28__length1;
			SdxGraphicsTextureRegion* _tmp29_;
			gint _tmp30_;
			gint _tmp31_;
			gint _tmp32_;
			SdxGraphicsTextureRegionFromRegion* _tmp33_;
			SdxGraphicsTextureRegion* _tmp34_;
			_tmp28_ = patches;
			_tmp28__length1 = patches_length1;
			_tmp29_ = region;
			_tmp30_ = left;
			_tmp31_ = middleWidth;
			_tmp32_ = top;
			_tmp33_ = sdx_graphics_texture_region_from_region_new (_tmp29_, _tmp30_, 0, _tmp31_, _tmp32_);
			_sdx_graphics_texture_region_release0 (_tmp28_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER]);
			_tmp28_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER] = (SdxGraphicsTextureRegion*) _tmp33_;
			_tmp34_ = _tmp28_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER];
		}
		_tmp35_ = right;
		if (_tmp35_ > 0) {
			SdxGraphicsTextureRegion** _tmp36_;
			gint _tmp36__length1;
			SdxGraphicsTextureRegion* _tmp37_;
			gint _tmp38_;
			gint _tmp39_;
			gint _tmp40_;
			gint _tmp41_;
			SdxGraphicsTextureRegionFromRegion* _tmp42_;
			SdxGraphicsTextureRegion* _tmp43_;
			_tmp36_ = patches;
			_tmp36__length1 = patches_length1;
			_tmp37_ = region;
			_tmp38_ = left;
			_tmp39_ = middleWidth;
			_tmp40_ = right;
			_tmp41_ = top;
			_tmp42_ = sdx_graphics_texture_region_from_region_new (_tmp37_, _tmp38_ + _tmp39_, 0, _tmp40_, _tmp41_);
			_sdx_graphics_texture_region_release0 (_tmp36_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT]);
			_tmp36_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT] = (SdxGraphicsTextureRegion*) _tmp42_;
			_tmp43_ = _tmp36_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
		}
	}
	_tmp44_ = middleHeight;
	if (_tmp44_ > 0) {
		gint _tmp45_;
		gint _tmp53_;
		gint _tmp62_;
		_tmp45_ = left;
		if (_tmp45_ > 0) {
			SdxGraphicsTextureRegion** _tmp46_;
			gint _tmp46__length1;
			SdxGraphicsTextureRegion* _tmp47_;
			gint _tmp48_;
			gint _tmp49_;
			gint _tmp50_;
			SdxGraphicsTextureRegionFromRegion* _tmp51_;
			SdxGraphicsTextureRegion* _tmp52_;
			_tmp46_ = patches;
			_tmp46__length1 = patches_length1;
			_tmp47_ = region;
			_tmp48_ = top;
			_tmp49_ = left;
			_tmp50_ = middleHeight;
			_tmp51_ = sdx_graphics_texture_region_from_region_new (_tmp47_, 0, _tmp48_, _tmp49_, _tmp50_);
			_sdx_graphics_texture_region_release0 (_tmp46_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT]);
			_tmp46_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT] = (SdxGraphicsTextureRegion*) _tmp51_;
			_tmp52_ = _tmp46_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT];
		}
		_tmp53_ = middleWidth;
		if (_tmp53_ > 0) {
			SdxGraphicsTextureRegion** _tmp54_;
			gint _tmp54__length1;
			SdxGraphicsTextureRegion* _tmp55_;
			gint _tmp56_;
			gint _tmp57_;
			gint _tmp58_;
			gint _tmp59_;
			SdxGraphicsTextureRegionFromRegion* _tmp60_;
			SdxGraphicsTextureRegion* _tmp61_;
			_tmp54_ = patches;
			_tmp54__length1 = patches_length1;
			_tmp55_ = region;
			_tmp56_ = left;
			_tmp57_ = top;
			_tmp58_ = middleWidth;
			_tmp59_ = middleHeight;
			_tmp60_ = sdx_graphics_texture_region_from_region_new (_tmp55_, _tmp56_, _tmp57_, _tmp58_, _tmp59_);
			_sdx_graphics_texture_region_release0 (_tmp54_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER]);
			_tmp54_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER] = (SdxGraphicsTextureRegion*) _tmp60_;
			_tmp61_ = _tmp54_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
		}
		_tmp62_ = right;
		if (_tmp62_ > 0) {
			SdxGraphicsTextureRegion** _tmp63_;
			gint _tmp63__length1;
			SdxGraphicsTextureRegion* _tmp64_;
			gint _tmp65_;
			gint _tmp66_;
			gint _tmp67_;
			gint _tmp68_;
			gint _tmp69_;
			SdxGraphicsTextureRegionFromRegion* _tmp70_;
			SdxGraphicsTextureRegion* _tmp71_;
			_tmp63_ = patches;
			_tmp63__length1 = patches_length1;
			_tmp64_ = region;
			_tmp65_ = left;
			_tmp66_ = middleWidth;
			_tmp67_ = top;
			_tmp68_ = right;
			_tmp69_ = middleHeight;
			_tmp70_ = sdx_graphics_texture_region_from_region_new (_tmp64_, _tmp65_ + _tmp66_, _tmp67_, _tmp68_, _tmp69_);
			_sdx_graphics_texture_region_release0 (_tmp63_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT]);
			_tmp63_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT] = (SdxGraphicsTextureRegion*) _tmp70_;
			_tmp71_ = _tmp63_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		}
	}
	_tmp72_ = bottom;
	if (_tmp72_ > 0) {
		gint _tmp73_;
		gint _tmp82_;
		gint _tmp92_;
		_tmp73_ = left;
		if (_tmp73_ > 0) {
			SdxGraphicsTextureRegion** _tmp74_;
			gint _tmp74__length1;
			SdxGraphicsTextureRegion* _tmp75_;
			gint _tmp76_;
			gint _tmp77_;
			gint _tmp78_;
			gint _tmp79_;
			SdxGraphicsTextureRegionFromRegion* _tmp80_;
			SdxGraphicsTextureRegion* _tmp81_;
			_tmp74_ = patches;
			_tmp74__length1 = patches_length1;
			_tmp75_ = region;
			_tmp76_ = top;
			_tmp77_ = middleHeight;
			_tmp78_ = left;
			_tmp79_ = bottom;
			_tmp80_ = sdx_graphics_texture_region_from_region_new (_tmp75_, 0, _tmp76_ + _tmp77_, _tmp78_, _tmp79_);
			_sdx_graphics_texture_region_release0 (_tmp74_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT]);
			_tmp74_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT] = (SdxGraphicsTextureRegion*) _tmp80_;
			_tmp81_ = _tmp74_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
		}
		_tmp82_ = middleWidth;
		if (_tmp82_ > 0) {
			SdxGraphicsTextureRegion** _tmp83_;
			gint _tmp83__length1;
			SdxGraphicsTextureRegion* _tmp84_;
			gint _tmp85_;
			gint _tmp86_;
			gint _tmp87_;
			gint _tmp88_;
			gint _tmp89_;
			SdxGraphicsTextureRegionFromRegion* _tmp90_;
			SdxGraphicsTextureRegion* _tmp91_;
			_tmp83_ = patches;
			_tmp83__length1 = patches_length1;
			_tmp84_ = region;
			_tmp85_ = left;
			_tmp86_ = top;
			_tmp87_ = middleHeight;
			_tmp88_ = middleWidth;
			_tmp89_ = bottom;
			_tmp90_ = sdx_graphics_texture_region_from_region_new (_tmp84_, _tmp85_, _tmp86_ + _tmp87_, _tmp88_, _tmp89_);
			_sdx_graphics_texture_region_release0 (_tmp83_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER]);
			_tmp83_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER] = (SdxGraphicsTextureRegion*) _tmp90_;
			_tmp91_ = _tmp83_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		}
		_tmp92_ = right;
		if (_tmp92_ > 0) {
			SdxGraphicsTextureRegion** _tmp93_;
			gint _tmp93__length1;
			SdxGraphicsTextureRegion* _tmp94_;
			gint _tmp95_;
			gint _tmp96_;
			gint _tmp97_;
			gint _tmp98_;
			gint _tmp99_;
			gint _tmp100_;
			SdxGraphicsTextureRegionFromRegion* _tmp101_;
			SdxGraphicsTextureRegion* _tmp102_;
			_tmp93_ = patches;
			_tmp93__length1 = patches_length1;
			_tmp94_ = region;
			_tmp95_ = left;
			_tmp96_ = middleWidth;
			_tmp97_ = top;
			_tmp98_ = middleHeight;
			_tmp99_ = right;
			_tmp100_ = bottom;
			_tmp101_ = sdx_graphics_texture_region_from_region_new (_tmp94_, _tmp95_ + _tmp96_, _tmp97_ + _tmp98_, _tmp99_, _tmp100_);
			_sdx_graphics_texture_region_release0 (_tmp93_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT]);
			_tmp93_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT] = (SdxGraphicsTextureRegion*) _tmp101_;
			_tmp102_ = _tmp93_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
		}
	}
	_tmp104_ = left;
	if (_tmp104_ == 0) {
		gint _tmp105_;
		_tmp105_ = middleWidth;
		_tmp103_ = _tmp105_ == 0;
	} else {
		_tmp103_ = FALSE;
	}
	if (_tmp103_) {
		SdxGraphicsTextureRegion** _tmp106_;
		gint _tmp106__length1;
		SdxGraphicsTextureRegion** _tmp107_;
		gint _tmp107__length1;
		SdxGraphicsTextureRegion* _tmp108_;
		SdxGraphicsTextureRegion* _tmp109_;
		SdxGraphicsTextureRegion* _tmp110_;
		SdxGraphicsTextureRegion** _tmp111_;
		gint _tmp111__length1;
		SdxGraphicsTextureRegion** _tmp112_;
		gint _tmp112__length1;
		SdxGraphicsTextureRegion* _tmp113_;
		SdxGraphicsTextureRegion* _tmp114_;
		SdxGraphicsTextureRegion* _tmp115_;
		SdxGraphicsTextureRegion** _tmp116_;
		gint _tmp116__length1;
		SdxGraphicsTextureRegion** _tmp117_;
		gint _tmp117__length1;
		SdxGraphicsTextureRegion* _tmp118_;
		SdxGraphicsTextureRegion* _tmp119_;
		SdxGraphicsTextureRegion* _tmp120_;
		SdxGraphicsTextureRegion** _tmp121_;
		gint _tmp121__length1;
		SdxGraphicsTextureRegion* _tmp122_;
		SdxGraphicsTextureRegion** _tmp123_;
		gint _tmp123__length1;
		SdxGraphicsTextureRegion* _tmp124_;
		SdxGraphicsTextureRegion** _tmp125_;
		gint _tmp125__length1;
		SdxGraphicsTextureRegion* _tmp126_;
		_tmp106_ = patches;
		_tmp106__length1 = patches_length1;
		_tmp107_ = patches;
		_tmp107__length1 = patches_length1;
		_tmp108_ = _tmp107_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
		_tmp109_ = _sdx_graphics_texture_region_retain0 (_tmp108_);
		_sdx_graphics_texture_region_release0 (_tmp106_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER]);
		_tmp106_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER] = _tmp109_;
		_tmp110_ = _tmp106_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER];
		_tmp111_ = patches;
		_tmp111__length1 = patches_length1;
		_tmp112_ = patches;
		_tmp112__length1 = patches_length1;
		_tmp113_ = _tmp112_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		_tmp114_ = _sdx_graphics_texture_region_retain0 (_tmp113_);
		_sdx_graphics_texture_region_release0 (_tmp111_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER]);
		_tmp111_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER] = _tmp114_;
		_tmp115_ = _tmp111_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
		_tmp116_ = patches;
		_tmp116__length1 = patches_length1;
		_tmp117_ = patches;
		_tmp117__length1 = patches_length1;
		_tmp118_ = _tmp117_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
		_tmp119_ = _sdx_graphics_texture_region_retain0 (_tmp118_);
		_sdx_graphics_texture_region_release0 (_tmp116_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER]);
		_tmp116_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER] = _tmp119_;
		_tmp120_ = _tmp116_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		_tmp121_ = patches;
		_tmp121__length1 = patches_length1;
		_sdx_graphics_texture_region_release0 (_tmp121_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT]);
		_tmp121_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT] = NULL;
		_tmp122_ = _tmp121_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
		_tmp123_ = patches;
		_tmp123__length1 = patches_length1;
		_sdx_graphics_texture_region_release0 (_tmp123_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT]);
		_tmp123_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT] = NULL;
		_tmp124_ = _tmp123_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		_tmp125_ = patches;
		_tmp125__length1 = patches_length1;
		_sdx_graphics_texture_region_release0 (_tmp125_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT]);
		_tmp125_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT] = NULL;
		_tmp126_ = _tmp125_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
	}
	_tmp128_ = top;
	if (_tmp128_ == 0) {
		gint _tmp129_;
		_tmp129_ = middleHeight;
		_tmp127_ = _tmp129_ == 0;
	} else {
		_tmp127_ = FALSE;
	}
	if (_tmp127_) {
		SdxGraphicsTextureRegion** _tmp130_;
		gint _tmp130__length1;
		SdxGraphicsTextureRegion** _tmp131_;
		gint _tmp131__length1;
		SdxGraphicsTextureRegion* _tmp132_;
		SdxGraphicsTextureRegion* _tmp133_;
		SdxGraphicsTextureRegion* _tmp134_;
		SdxGraphicsTextureRegion** _tmp135_;
		gint _tmp135__length1;
		SdxGraphicsTextureRegion** _tmp136_;
		gint _tmp136__length1;
		SdxGraphicsTextureRegion* _tmp137_;
		SdxGraphicsTextureRegion* _tmp138_;
		SdxGraphicsTextureRegion* _tmp139_;
		SdxGraphicsTextureRegion** _tmp140_;
		gint _tmp140__length1;
		SdxGraphicsTextureRegion** _tmp141_;
		gint _tmp141__length1;
		SdxGraphicsTextureRegion* _tmp142_;
		SdxGraphicsTextureRegion* _tmp143_;
		SdxGraphicsTextureRegion* _tmp144_;
		SdxGraphicsTextureRegion** _tmp145_;
		gint _tmp145__length1;
		SdxGraphicsTextureRegion* _tmp146_;
		SdxGraphicsTextureRegion** _tmp147_;
		gint _tmp147__length1;
		SdxGraphicsTextureRegion* _tmp148_;
		SdxGraphicsTextureRegion** _tmp149_;
		gint _tmp149__length1;
		SdxGraphicsTextureRegion* _tmp150_;
		_tmp130_ = patches;
		_tmp130__length1 = patches_length1;
		_tmp131_ = patches;
		_tmp131__length1 = patches_length1;
		_tmp132_ = _tmp131_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
		_tmp133_ = _sdx_graphics_texture_region_retain0 (_tmp132_);
		_sdx_graphics_texture_region_release0 (_tmp130_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT]);
		_tmp130_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT] = _tmp133_;
		_tmp134_ = _tmp130_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT];
		_tmp135_ = patches;
		_tmp135__length1 = patches_length1;
		_tmp136_ = patches;
		_tmp136__length1 = patches_length1;
		_tmp137_ = _tmp136_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		_tmp138_ = _sdx_graphics_texture_region_retain0 (_tmp137_);
		_sdx_graphics_texture_region_release0 (_tmp135_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER]);
		_tmp135_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER] = _tmp138_;
		_tmp139_ = _tmp135_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
		_tmp140_ = patches;
		_tmp140__length1 = patches_length1;
		_tmp141_ = patches;
		_tmp141__length1 = patches_length1;
		_tmp142_ = _tmp141_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
		_tmp143_ = _sdx_graphics_texture_region_retain0 (_tmp142_);
		_sdx_graphics_texture_region_release0 (_tmp140_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT]);
		_tmp140_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT] = _tmp143_;
		_tmp144_ = _tmp140_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		_tmp145_ = patches;
		_tmp145__length1 = patches_length1;
		_sdx_graphics_texture_region_release0 (_tmp145_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT]);
		_tmp145_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT] = NULL;
		_tmp146_ = _tmp145_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
		_tmp147_ = patches;
		_tmp147__length1 = patches_length1;
		_sdx_graphics_texture_region_release0 (_tmp147_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER]);
		_tmp147_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER] = NULL;
		_tmp148_ = _tmp147_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		_tmp149_ = patches;
		_tmp149__length1 = patches_length1;
		_sdx_graphics_texture_region_release0 (_tmp149_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT]);
		_tmp149_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT] = NULL;
		_tmp150_ = _tmp149_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
	}
	_tmp151_ = patches;
	_tmp151__length1 = patches_length1;
	sdx_graphics_nine_patch_Load (self, _tmp151_, _tmp151__length1);
	patches = (_vala_array_free (patches, patches_length1, (GDestroyNotify) sdx_graphics_texture_region_release), NULL);
	return self;
}


void sdx_graphics_nine_patch_Load (SdxGraphicsNinePatch* self, SdxGraphicsTextureRegion** patches, int patches_length1) {
	SDL_Color color = {0};
	SdxGraphicsTextureRegion** _tmp0_;
	gint _tmp0__length1;
	SdxGraphicsTextureRegion* _tmp1_;
	SdxGraphicsTextureRegion** _tmp16_;
	gint _tmp16__length1;
	SdxGraphicsTextureRegion* _tmp17_;
	SdxGraphicsTextureRegion** _tmp32_;
	gint _tmp32__length1;
	SdxGraphicsTextureRegion* _tmp33_;
	SdxGraphicsTextureRegion** _tmp48_;
	gint _tmp48__length1;
	SdxGraphicsTextureRegion* _tmp49_;
	SdxGraphicsTextureRegion** _tmp64_;
	gint _tmp64__length1;
	SdxGraphicsTextureRegion* _tmp65_;
	SdxGraphicsTextureRegion** _tmp80_;
	gint _tmp80__length1;
	SdxGraphicsTextureRegion* _tmp81_;
	SdxGraphicsTextureRegion** _tmp96_;
	gint _tmp96__length1;
	SdxGraphicsTextureRegion* _tmp97_;
	SdxGraphicsTextureRegion** _tmp108_;
	gint _tmp108__length1;
	SdxGraphicsTextureRegion* _tmp109_;
	SdxGraphicsTextureRegion** _tmp124_;
	gint _tmp124__length1;
	SdxGraphicsTextureRegion* _tmp125_;
	g_return_if_fail (self != NULL);
	color = SDX_COLOR_White;
	_tmp0_ = patches;
	_tmp0__length1 = patches_length1;
	_tmp1_ = _tmp0_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT];
	if (_tmp1_ != NULL) {
		SdxGraphicsTextureRegion** _tmp2_;
		gint _tmp2__length1;
		SdxGraphicsTextureRegion* _tmp3_;
		SDL_Color _tmp4_;
		gint _tmp5_;
		gfloat _tmp6_;
		SdxGraphicsTextureRegion** _tmp7_;
		gint _tmp7__length1;
		SdxGraphicsTextureRegion* _tmp8_;
		gint _tmp9_;
		gdouble _tmp10_;
		gfloat _tmp11_;
		SdxGraphicsTextureRegion** _tmp12_;
		gint _tmp12__length1;
		SdxGraphicsTextureRegion* _tmp13_;
		gint _tmp14_;
		gdouble _tmp15_;
		_tmp2_ = patches;
		_tmp2__length1 = patches_length1;
		_tmp3_ = _tmp2_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT];
		_tmp4_ = color;
		_tmp5_ = sdx_graphics_nine_patch_Add (self, _tmp3_, _tmp4_, FALSE, FALSE);
		self->topLeft = _tmp5_;
		_tmp6_ = self->leftWidth;
		_tmp7_ = patches;
		_tmp7__length1 = patches_length1;
		_tmp8_ = _tmp7_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT];
		_tmp9_ = sdx_graphics_texture_region_GetRegionWidth (_tmp8_);
		_tmp10_ = fmax ((gdouble) _tmp6_, (gdouble) _tmp9_);
		self->leftWidth = (gfloat) ((gint) _tmp10_);
		_tmp11_ = self->topHeight;
		_tmp12_ = patches;
		_tmp12__length1 = patches_length1;
		_tmp13_ = _tmp12_[SDX_GRAPHICS_NINE_PATCH_TOP_LEFT];
		_tmp14_ = sdx_graphics_texture_region_GetRegionHeight (_tmp13_);
		_tmp15_ = fmax ((gdouble) _tmp11_, (gdouble) _tmp14_);
		self->topHeight = (gfloat) ((gint) _tmp15_);
	}
	_tmp16_ = patches;
	_tmp16__length1 = patches_length1;
	_tmp17_ = _tmp16_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER];
	if (_tmp17_ != NULL) {
		SdxGraphicsTextureRegion** _tmp18_;
		gint _tmp18__length1;
		SdxGraphicsTextureRegion* _tmp19_;
		SDL_Color _tmp20_;
		gint _tmp21_;
		gfloat _tmp22_;
		SdxGraphicsTextureRegion** _tmp23_;
		gint _tmp23__length1;
		SdxGraphicsTextureRegion* _tmp24_;
		gint _tmp25_;
		gdouble _tmp26_;
		gfloat _tmp27_;
		SdxGraphicsTextureRegion** _tmp28_;
		gint _tmp28__length1;
		SdxGraphicsTextureRegion* _tmp29_;
		gint _tmp30_;
		gdouble _tmp31_;
		_tmp18_ = patches;
		_tmp18__length1 = patches_length1;
		_tmp19_ = _tmp18_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER];
		_tmp20_ = color;
		_tmp21_ = sdx_graphics_nine_patch_Add (self, _tmp19_, _tmp20_, TRUE, FALSE);
		self->topCenter = _tmp21_;
		_tmp22_ = self->middleWidth;
		_tmp23_ = patches;
		_tmp23__length1 = patches_length1;
		_tmp24_ = _tmp23_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER];
		_tmp25_ = sdx_graphics_texture_region_GetRegionWidth (_tmp24_);
		_tmp26_ = fmax ((gdouble) _tmp22_, (gdouble) _tmp25_);
		self->middleWidth = (gfloat) ((gint) _tmp26_);
		_tmp27_ = self->topHeight;
		_tmp28_ = patches;
		_tmp28__length1 = patches_length1;
		_tmp29_ = _tmp28_[SDX_GRAPHICS_NINE_PATCH_TOP_CENTER];
		_tmp30_ = sdx_graphics_texture_region_GetRegionHeight (_tmp29_);
		_tmp31_ = fmax ((gdouble) _tmp27_, (gdouble) _tmp30_);
		self->topHeight = (gfloat) ((gint) _tmp31_);
	}
	_tmp32_ = patches;
	_tmp32__length1 = patches_length1;
	_tmp33_ = _tmp32_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
	if (_tmp33_ != NULL) {
		SdxGraphicsTextureRegion** _tmp34_;
		gint _tmp34__length1;
		SdxGraphicsTextureRegion* _tmp35_;
		SDL_Color _tmp36_;
		gint _tmp37_;
		gfloat _tmp38_;
		SdxGraphicsTextureRegion** _tmp39_;
		gint _tmp39__length1;
		SdxGraphicsTextureRegion* _tmp40_;
		gint _tmp41_;
		gdouble _tmp42_;
		gfloat _tmp43_;
		SdxGraphicsTextureRegion** _tmp44_;
		gint _tmp44__length1;
		SdxGraphicsTextureRegion* _tmp45_;
		gint _tmp46_;
		gdouble _tmp47_;
		_tmp34_ = patches;
		_tmp34__length1 = patches_length1;
		_tmp35_ = _tmp34_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
		_tmp36_ = color;
		_tmp37_ = sdx_graphics_nine_patch_Add (self, _tmp35_, _tmp36_, FALSE, FALSE);
		self->topRight = _tmp37_;
		_tmp38_ = self->rightWidth;
		_tmp39_ = patches;
		_tmp39__length1 = patches_length1;
		_tmp40_ = _tmp39_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
		_tmp41_ = sdx_graphics_texture_region_GetRegionWidth (_tmp40_);
		_tmp42_ = fmax ((gdouble) _tmp38_, (gdouble) _tmp41_);
		self->rightWidth = (gfloat) ((gint) _tmp42_);
		_tmp43_ = self->topHeight;
		_tmp44_ = patches;
		_tmp44__length1 = patches_length1;
		_tmp45_ = _tmp44_[SDX_GRAPHICS_NINE_PATCH_TOP_RIGHT];
		_tmp46_ = sdx_graphics_texture_region_GetRegionHeight (_tmp45_);
		_tmp47_ = fmax ((gdouble) _tmp43_, (gdouble) _tmp46_);
		self->topHeight = (gfloat) ((gint) _tmp47_);
	}
	_tmp48_ = patches;
	_tmp48__length1 = patches_length1;
	_tmp49_ = _tmp48_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT];
	if (_tmp49_ != NULL) {
		SdxGraphicsTextureRegion** _tmp50_;
		gint _tmp50__length1;
		SdxGraphicsTextureRegion* _tmp51_;
		SDL_Color _tmp52_;
		gint _tmp53_;
		gfloat _tmp54_;
		SdxGraphicsTextureRegion** _tmp55_;
		gint _tmp55__length1;
		SdxGraphicsTextureRegion* _tmp56_;
		gint _tmp57_;
		gdouble _tmp58_;
		gfloat _tmp59_;
		SdxGraphicsTextureRegion** _tmp60_;
		gint _tmp60__length1;
		SdxGraphicsTextureRegion* _tmp61_;
		gint _tmp62_;
		gdouble _tmp63_;
		_tmp50_ = patches;
		_tmp50__length1 = patches_length1;
		_tmp51_ = _tmp50_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT];
		_tmp52_ = color;
		_tmp53_ = sdx_graphics_nine_patch_Add (self, _tmp51_, _tmp52_, FALSE, TRUE);
		self->middleLeft = _tmp53_;
		_tmp54_ = self->leftWidth;
		_tmp55_ = patches;
		_tmp55__length1 = patches_length1;
		_tmp56_ = _tmp55_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT];
		_tmp57_ = sdx_graphics_texture_region_GetRegionWidth (_tmp56_);
		_tmp58_ = fmax ((gdouble) _tmp54_, (gdouble) _tmp57_);
		self->leftWidth = (gfloat) ((gint) _tmp58_);
		_tmp59_ = self->middleHeight;
		_tmp60_ = patches;
		_tmp60__length1 = patches_length1;
		_tmp61_ = _tmp60_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_LEFT];
		_tmp62_ = sdx_graphics_texture_region_GetRegionHeight (_tmp61_);
		_tmp63_ = fmax ((gdouble) _tmp59_, (gdouble) _tmp62_);
		self->middleHeight = (gfloat) ((gint) _tmp63_);
	}
	_tmp64_ = patches;
	_tmp64__length1 = patches_length1;
	_tmp65_ = _tmp64_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
	if (_tmp65_ != NULL) {
		SdxGraphicsTextureRegion** _tmp66_;
		gint _tmp66__length1;
		SdxGraphicsTextureRegion* _tmp67_;
		SDL_Color _tmp68_;
		gint _tmp69_;
		gfloat _tmp70_;
		SdxGraphicsTextureRegion** _tmp71_;
		gint _tmp71__length1;
		SdxGraphicsTextureRegion* _tmp72_;
		gint _tmp73_;
		gdouble _tmp74_;
		gfloat _tmp75_;
		SdxGraphicsTextureRegion** _tmp76_;
		gint _tmp76__length1;
		SdxGraphicsTextureRegion* _tmp77_;
		gint _tmp78_;
		gdouble _tmp79_;
		_tmp66_ = patches;
		_tmp66__length1 = patches_length1;
		_tmp67_ = _tmp66_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
		_tmp68_ = color;
		_tmp69_ = sdx_graphics_nine_patch_Add (self, _tmp67_, _tmp68_, TRUE, TRUE);
		self->middleCenter = _tmp69_;
		_tmp70_ = self->middleWidth;
		_tmp71_ = patches;
		_tmp71__length1 = patches_length1;
		_tmp72_ = _tmp71_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
		_tmp73_ = sdx_graphics_texture_region_GetRegionWidth (_tmp72_);
		_tmp74_ = fmax ((gdouble) _tmp70_, (gdouble) _tmp73_);
		self->middleWidth = (gfloat) ((gint) _tmp74_);
		_tmp75_ = self->middleHeight;
		_tmp76_ = patches;
		_tmp76__length1 = patches_length1;
		_tmp77_ = _tmp76_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_CENTER];
		_tmp78_ = sdx_graphics_texture_region_GetRegionHeight (_tmp77_);
		_tmp79_ = fmax ((gdouble) _tmp75_, (gdouble) _tmp78_);
		self->middleHeight = (gfloat) ((gint) _tmp79_);
	}
	_tmp80_ = patches;
	_tmp80__length1 = patches_length1;
	_tmp81_ = _tmp80_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
	if (_tmp81_ != NULL) {
		SdxGraphicsTextureRegion** _tmp82_;
		gint _tmp82__length1;
		SdxGraphicsTextureRegion* _tmp83_;
		SDL_Color _tmp84_;
		gint _tmp85_;
		gfloat _tmp86_;
		SdxGraphicsTextureRegion** _tmp87_;
		gint _tmp87__length1;
		SdxGraphicsTextureRegion* _tmp88_;
		gint _tmp89_;
		gdouble _tmp90_;
		gfloat _tmp91_;
		SdxGraphicsTextureRegion** _tmp92_;
		gint _tmp92__length1;
		SdxGraphicsTextureRegion* _tmp93_;
		gint _tmp94_;
		gdouble _tmp95_;
		_tmp82_ = patches;
		_tmp82__length1 = patches_length1;
		_tmp83_ = _tmp82_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		_tmp84_ = color;
		_tmp85_ = sdx_graphics_nine_patch_Add (self, _tmp83_, _tmp84_, FALSE, TRUE);
		self->middleRight = _tmp85_;
		_tmp86_ = self->rightWidth;
		_tmp87_ = patches;
		_tmp87__length1 = patches_length1;
		_tmp88_ = _tmp87_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		_tmp89_ = sdx_graphics_texture_region_GetRegionWidth (_tmp88_);
		_tmp90_ = fmax ((gdouble) _tmp86_, (gdouble) _tmp89_);
		self->rightWidth = (gfloat) ((gint) _tmp90_);
		_tmp91_ = self->middleHeight;
		_tmp92_ = patches;
		_tmp92__length1 = patches_length1;
		_tmp93_ = _tmp92_[SDX_GRAPHICS_NINE_PATCH_MIDDLE_RIGHT];
		_tmp94_ = sdx_graphics_texture_region_GetRegionHeight (_tmp93_);
		_tmp95_ = fmax ((gdouble) _tmp91_, (gdouble) _tmp94_);
		self->middleHeight = (gfloat) ((gint) _tmp95_);
	}
	_tmp96_ = patches;
	_tmp96__length1 = patches_length1;
	_tmp97_ = _tmp96_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
	if (_tmp97_ != NULL) {
		SdxGraphicsTextureRegion** _tmp98_;
		gint _tmp98__length1;
		SdxGraphicsTextureRegion* _tmp99_;
		SDL_Color _tmp100_;
		gint _tmp101_;
		SdxGraphicsTextureRegion** _tmp102_;
		gint _tmp102__length1;
		SdxGraphicsTextureRegion* _tmp103_;
		gint _tmp104_;
		SdxGraphicsTextureRegion** _tmp105_;
		gint _tmp105__length1;
		SdxGraphicsTextureRegion* _tmp106_;
		gint _tmp107_;
		_tmp98_ = patches;
		_tmp98__length1 = patches_length1;
		_tmp99_ = _tmp98_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
		_tmp100_ = color;
		_tmp101_ = sdx_graphics_nine_patch_Add (self, _tmp99_, _tmp100_, FALSE, FALSE);
		self->bottomLeft = _tmp101_;
		_tmp102_ = patches;
		_tmp102__length1 = patches_length1;
		_tmp103_ = _tmp102_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
		_tmp104_ = sdx_graphics_texture_region_GetRegionWidth (_tmp103_);
		self->leftWidth = (gfloat) _tmp104_;
		_tmp105_ = patches;
		_tmp105__length1 = patches_length1;
		_tmp106_ = _tmp105_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_LEFT];
		_tmp107_ = sdx_graphics_texture_region_GetRegionHeight (_tmp106_);
		self->bottomHeight = (gfloat) _tmp107_;
	}
	_tmp108_ = patches;
	_tmp108__length1 = patches_length1;
	_tmp109_ = _tmp108_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
	if (_tmp109_ != NULL) {
		SdxGraphicsTextureRegion** _tmp110_;
		gint _tmp110__length1;
		SdxGraphicsTextureRegion* _tmp111_;
		SDL_Color _tmp112_;
		gint _tmp113_;
		gfloat _tmp114_;
		SdxGraphicsTextureRegion** _tmp115_;
		gint _tmp115__length1;
		SdxGraphicsTextureRegion* _tmp116_;
		gint _tmp117_;
		gdouble _tmp118_;
		gfloat _tmp119_;
		SdxGraphicsTextureRegion** _tmp120_;
		gint _tmp120__length1;
		SdxGraphicsTextureRegion* _tmp121_;
		gint _tmp122_;
		gdouble _tmp123_;
		_tmp110_ = patches;
		_tmp110__length1 = patches_length1;
		_tmp111_ = _tmp110_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		_tmp112_ = color;
		_tmp113_ = sdx_graphics_nine_patch_Add (self, _tmp111_, _tmp112_, TRUE, FALSE);
		self->bottomCenter = _tmp113_;
		_tmp114_ = self->middleWidth;
		_tmp115_ = patches;
		_tmp115__length1 = patches_length1;
		_tmp116_ = _tmp115_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		_tmp117_ = sdx_graphics_texture_region_GetRegionWidth (_tmp116_);
		_tmp118_ = fmax ((gdouble) _tmp114_, (gdouble) _tmp117_);
		self->middleWidth = (gfloat) ((gint) _tmp118_);
		_tmp119_ = self->bottomHeight;
		_tmp120_ = patches;
		_tmp120__length1 = patches_length1;
		_tmp121_ = _tmp120_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_CENTER];
		_tmp122_ = sdx_graphics_texture_region_GetRegionHeight (_tmp121_);
		_tmp123_ = fmax ((gdouble) _tmp119_, (gdouble) _tmp122_);
		self->bottomHeight = (gfloat) ((gint) _tmp123_);
	}
	_tmp124_ = patches;
	_tmp124__length1 = patches_length1;
	_tmp125_ = _tmp124_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
	if (_tmp125_ != NULL) {
		SdxGraphicsTextureRegion** _tmp126_;
		gint _tmp126__length1;
		SdxGraphicsTextureRegion* _tmp127_;
		SDL_Color _tmp128_;
		gint _tmp129_;
		gfloat _tmp130_;
		SdxGraphicsTextureRegion** _tmp131_;
		gint _tmp131__length1;
		SdxGraphicsTextureRegion* _tmp132_;
		gint _tmp133_;
		gdouble _tmp134_;
		gfloat _tmp135_;
		SdxGraphicsTextureRegion** _tmp136_;
		gint _tmp136__length1;
		SdxGraphicsTextureRegion* _tmp137_;
		gint _tmp138_;
		gdouble _tmp139_;
		_tmp126_ = patches;
		_tmp126__length1 = patches_length1;
		_tmp127_ = _tmp126_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
		_tmp128_ = color;
		_tmp129_ = sdx_graphics_nine_patch_Add (self, _tmp127_, _tmp128_, FALSE, FALSE);
		self->bottomRight = _tmp129_;
		_tmp130_ = self->rightWidth;
		_tmp131_ = patches;
		_tmp131__length1 = patches_length1;
		_tmp132_ = _tmp131_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
		_tmp133_ = sdx_graphics_texture_region_GetRegionWidth (_tmp132_);
		_tmp134_ = fmax ((gdouble) _tmp130_, (gdouble) _tmp133_);
		self->rightWidth = (gfloat) ((gint) _tmp134_);
		_tmp135_ = self->bottomHeight;
		_tmp136_ = patches;
		_tmp136__length1 = patches_length1;
		_tmp137_ = _tmp136_[SDX_GRAPHICS_NINE_PATCH_BOTTOM_RIGHT];
		_tmp138_ = sdx_graphics_texture_region_GetRegionHeight (_tmp137_);
		_tmp139_ = fmax ((gdouble) _tmp135_, (gdouble) _tmp138_);
		self->bottomHeight = (gfloat) ((gint) _tmp139_);
	}
}


static gpointer _sdx_graphics_surface_retain0 (gpointer self) {
	return self ? sdx_graphics_surface_retain (self) : NULL;
}


gint sdx_graphics_nine_patch_Add (SdxGraphicsNinePatch* self, SdxGraphicsTextureRegion* region, SDL_Color color, gboolean isStretchW, gboolean isStretchH) {
	gint result = 0;
	SdxGraphicsSurfaceTextureSurface* _tmp0_;
	gfloat u = 0.0F;
	SdxGraphicsTextureRegion* _tmp9_;
	gfloat _tmp10_;
	gfloat v = 0.0F;
	SdxGraphicsTextureRegion* _tmp11_;
	gfloat _tmp12_;
	gfloat u2 = 0.0F;
	SdxGraphicsTextureRegion* _tmp13_;
	gfloat _tmp14_;
	gfloat v2 = 0.0F;
	SdxGraphicsTextureRegion* _tmp15_;
	gfloat _tmp16_;
	gboolean _tmp17_;
	gboolean _tmp25_;
	gint _tmp33_;
	SdxGraphicsTextureRegion* _tmp34_;
	gint _tmp35_;
	gint _tmp36_;
	SdxGraphicsTextureRegion* _tmp37_;
	gint _tmp38_;
	gint _tmp39_;
	SdxGraphicsTextureRegion* _tmp40_;
	gint _tmp41_;
	SdxGraphicsTextureRegion* _tmp42_;
	gint _tmp43_;
	SDL_Rect _tmp44_ = {0};
	SdxGraphicsTextureRegion* _tmp45_;
	gint _tmp46_;
	SdxGraphicsTextureRegion* _tmp47_;
	gint _tmp48_;
	SdxGraphicsTextureRegion* _tmp49_;
	gint _tmp50_;
	SdxGraphicsTextureRegion* _tmp51_;
	gint _tmp52_;
	SDL_Rect _tmp53_ = {0};
	SdxGraphicsBlit _tmp54_ = {0};
	SdxGraphicsBlit _tmp55_;
	gint _tmp56_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (region != NULL, 0);
	_tmp0_ = self->texture;
	if (_tmp0_ == NULL) {
		SdxGraphicsTextureRegion* _tmp1_;
		SdxGraphicsSurfaceTextureSurface* _tmp2_;
		SdxGraphicsSurfaceTextureSurface* _tmp3_;
		_tmp1_ = region;
		_tmp2_ = _tmp1_->texture;
		_tmp3_ = _sdx_graphics_surface_retain0 (_tmp2_);
		_sdx_graphics_surface_release0 (self->texture);
		self->texture = _tmp3_;
	} else {
		SdxGraphicsSurfaceTextureSurface* _tmp4_;
		SdxGraphicsTextureRegion* _tmp5_;
		SdxGraphicsSurfaceTextureSurface* _tmp6_;
		_tmp4_ = self->texture;
		_tmp5_ = region;
		_tmp6_ = _tmp5_->texture;
		if (_tmp4_ != _tmp6_) {
			GError* _tmp7_;
			gint _tmp8_ = 0;
			_tmp7_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_IllegalArgumentException, "All regions must be from the same texture.");
			_inner_error_ = _tmp7_;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return _tmp8_;
		}
	}
	_tmp9_ = region;
	_tmp10_ = _tmp9_->u;
	u = _tmp10_;
	_tmp11_ = region;
	_tmp12_ = _tmp11_->v2;
	v = _tmp12_;
	_tmp13_ = region;
	_tmp14_ = _tmp13_->u2;
	u2 = _tmp14_;
	_tmp15_ = region;
	_tmp16_ = _tmp15_->v;
	v2 = _tmp16_;
	_tmp17_ = isStretchW;
	if (_tmp17_) {
		gfloat halfTexelWidth = 0.0F;
		SdxGraphicsSurfaceTextureSurface* _tmp18_;
		gint _tmp19_;
		gint _tmp20_;
		gfloat _tmp21_;
		gfloat _tmp22_;
		gfloat _tmp23_;
		gfloat _tmp24_;
		_tmp18_ = self->texture;
		_tmp19_ = sdx_graphics_surface_get_width ((SdxGraphicsSurface*) _tmp18_);
		_tmp20_ = _tmp19_;
		halfTexelWidth = (0.5f * 1.0f) / _tmp20_;
		_tmp21_ = u;
		_tmp22_ = halfTexelWidth;
		u = _tmp21_ + _tmp22_;
		_tmp23_ = u2;
		_tmp24_ = halfTexelWidth;
		u2 = _tmp23_ - _tmp24_;
	}
	_tmp25_ = isStretchH;
	if (_tmp25_) {
		gfloat halfTexelHeight = 0.0F;
		SdxGraphicsSurfaceTextureSurface* _tmp26_;
		gint _tmp27_;
		gint _tmp28_;
		gfloat _tmp29_;
		gfloat _tmp30_;
		gfloat _tmp31_;
		gfloat _tmp32_;
		_tmp26_ = self->texture;
		_tmp27_ = sdx_graphics_surface_get_height ((SdxGraphicsSurface*) _tmp26_);
		_tmp28_ = _tmp27_;
		halfTexelHeight = (0.5f * 1.0f) / _tmp28_;
		_tmp29_ = v;
		_tmp30_ = halfTexelHeight;
		v = _tmp29_ - _tmp30_;
		_tmp31_ = v2;
		_tmp32_ = halfTexelHeight;
		v2 = _tmp31_ + _tmp32_;
	}
	_tmp33_ = self->idx;
	_tmp34_ = region;
	_tmp35_ = _tmp34_->left;
	_tmp36_ = self->sourceLeft;
	_tmp37_ = region;
	_tmp38_ = _tmp37_->top;
	_tmp39_ = self->sourceTop;
	_tmp40_ = region;
	_tmp41_ = _tmp40_->width;
	_tmp42_ = region;
	_tmp43_ = _tmp42_->height;
	memset (&_tmp44_, 0, sizeof (SDL_Rect));
	_tmp44_.y = _tmp35_ + _tmp36_;
	_tmp44_.x = _tmp38_ + _tmp39_;
	_tmp44_.w = (guint) _tmp41_;
	_tmp44_.h = (guint) _tmp43_;
	_tmp45_ = region;
	_tmp46_ = _tmp45_->left;
	_tmp47_ = region;
	_tmp48_ = _tmp47_->top;
	_tmp49_ = region;
	_tmp50_ = _tmp49_->width;
	_tmp51_ = region;
	_tmp52_ = _tmp51_->height;
	memset (&_tmp53_, 0, sizeof (SDL_Rect));
	_tmp53_.y = _tmp46_;
	_tmp53_.x = _tmp48_;
	_tmp53_.w = (guint) _tmp50_;
	_tmp53_.h = (guint) _tmp52_;
	_tmp54_.source = _tmp44_;
	_tmp54_.dest = _tmp53_;
	_tmp54_.flip = 0;
	self->slice[_tmp33_] = _tmp54_;
	_tmp55_ = self->slice[_tmp33_];
	_tmp56_ = self->idx;
	self->idx = _tmp56_ + 1;
	result = _tmp56_;
	return result;
}


void sdx_graphics_nine_patch_SetColor (SdxGraphicsNinePatch* self, SDL_Color color) {
	SDL_Color _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = color;
	self->color = _tmp0_;
}


SDL_Color sdx_graphics_nine_patch_GetColor (SdxGraphicsNinePatch* self) {
	SDL_Color result = {0};
	SDL_Color _tmp0_;
	_tmp0_ = self->color;
	result = _tmp0_;
	return result;
}


gfloat sdx_graphics_nine_patch_GetLeftWidth (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->leftWidth;
	result = _tmp0_;
	return result;
}


/** 
         * Set the draw-time width of the three left edge patches 
         */
void sdx_graphics_nine_patch_SetLeftWidth (SdxGraphicsNinePatch* self, gfloat leftWidth) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = leftWidth;
	self->leftWidth = _tmp0_;
}


gfloat sdx_graphics_nine_patch_GetRightWidth (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->rightWidth;
	result = _tmp0_;
	return result;
}


/** 
         * Set the draw-time width of the three right edge patches 
         */
void sdx_graphics_nine_patch_SetRightWidth (SdxGraphicsNinePatch* self, gfloat rightWidth) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = rightWidth;
	self->rightWidth = _tmp0_;
}


gfloat sdx_graphics_nine_patch_GetTopHeight (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->topHeight;
	result = _tmp0_;
	return result;
}


/** 
         * Set the draw-time height of the three top edge patches 
         */
void sdx_graphics_nine_patch_SetTopHeight (SdxGraphicsNinePatch* self, gfloat topHeight) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = topHeight;
	self->topHeight = _tmp0_;
}


gfloat sdx_graphics_nine_patch_GetBottomHeight (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->bottomHeight;
	result = _tmp0_;
	return result;
}


/** 
         * Set the draw-time height of the three bottom edge patches 
         */
void sdx_graphics_nine_patch_SetBottomHeight (SdxGraphicsNinePatch* self, gfloat bottomHeight) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = bottomHeight;
	self->bottomHeight = _tmp0_;
}


gfloat sdx_graphics_nine_patch_GetMiddleWidth (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->middleWidth;
	result = _tmp0_;
	return result;
}


/** 
         * Set the width of the middle column of the patch. At render time, this is implicitly the requested render-width of the
         * entire nine patch, minus the left and right width. This value is only used for computing the link #GetTotalWidth() default
         * total width. 
         */
void sdx_graphics_nine_patch_SetMiddleWidth (SdxGraphicsNinePatch* self, gfloat middleWidth) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = middleWidth;
	self->middleWidth = _tmp0_;
}


gfloat sdx_graphics_nine_patch_GetMiddleHeight (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->middleHeight;
	result = _tmp0_;
	return result;
}


/** 
         * Set the height of the middle row of the patch. At render time, this is implicitly the requested render-height of the entire
         * nine patch, minus the top and bottom height. This value is only used for computing the link #GetTotalHeight() default
         * total height. 
         */
void sdx_graphics_nine_patch_SetMiddleHeight (SdxGraphicsNinePatch* self, gfloat middleHeight) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = middleHeight;
	self->middleHeight = _tmp0_;
}


gfloat sdx_graphics_nine_patch_GetTotalWidth (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->leftWidth;
	_tmp1_ = self->middleWidth;
	_tmp2_ = self->rightWidth;
	result = (_tmp0_ + _tmp1_) + _tmp2_;
	return result;
}


gfloat sdx_graphics_nine_patch_GetTotalHeight (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->topHeight;
	_tmp1_ = self->middleHeight;
	_tmp2_ = self->bottomHeight;
	result = (_tmp0_ + _tmp1_) + _tmp2_;
	return result;
}


/** 
         * Set the padding for content inside this ninepatch. By default the padding is set to match the exterior of the ninepatch, so
         * the content should fit exactly within the middle patch. 
         */
void sdx_graphics_nine_patch_SetPadding (SdxGraphicsNinePatch* self, gfloat left, gfloat right, gfloat top, gfloat bottom) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = left;
	self->padLeft = _tmp0_;
	_tmp1_ = right;
	self->padRight = _tmp1_;
	_tmp2_ = top;
	self->padTop = _tmp2_;
	_tmp3_ = bottom;
	self->padBottom = _tmp3_;
}


/** 
         * Returns the left padding if set, else returns link #GetLeftWidth(). 
         */
gfloat sdx_graphics_nine_patch_GetPadLeft (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp2_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->padLeft;
	if (_tmp0_ == ((gfloat) -1)) {
		gfloat _tmp1_;
		_tmp1_ = sdx_graphics_nine_patch_GetLeftWidth (self);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->padLeft;
	result = _tmp2_;
	return result;
}


/** 
         * See link #setPadding(float, float, float, float) 
         */
void sdx_graphics_nine_patch_SetPadLeft (SdxGraphicsNinePatch* self, gfloat left) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = left;
	self->padLeft = _tmp0_;
}


/** 
         * Returns the right padding if set, else returns link #GetRightWidth(). 
         */
gfloat sdx_graphics_nine_patch_GetPadRight (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp2_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->padRight;
	if (_tmp0_ == ((gfloat) -1)) {
		gfloat _tmp1_;
		_tmp1_ = sdx_graphics_nine_patch_GetRightWidth (self);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->padRight;
	result = _tmp2_;
	return result;
}


/** 
         * See link #setPadding(float, float, float, float) 
         */
void sdx_graphics_nine_patch_SetPadRight (SdxGraphicsNinePatch* self, gfloat right) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = right;
	self->padRight = _tmp0_;
}


/** 
         * Returns the top padding if set, else returns link #GetTopHeight(). 
         */
gfloat sdx_graphics_nine_patch_GetPadTop (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp2_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->padTop;
	if (_tmp0_ == ((gfloat) -1)) {
		gfloat _tmp1_;
		_tmp1_ = sdx_graphics_nine_patch_GetTopHeight (self);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->padTop;
	result = _tmp2_;
	return result;
}


/** 
         * See link #setPadding(float, float, float, float) 
         */
void sdx_graphics_nine_patch_SetPadTop (SdxGraphicsNinePatch* self, gfloat top) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = top;
	self->padTop = _tmp0_;
}


/** 
         * Returns the bottom padding if set, else returns link #GetBottomHeight(). 
         */
gfloat sdx_graphics_nine_patch_GetPadBottom (SdxGraphicsNinePatch* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp2_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->padBottom;
	if (_tmp0_ == ((gfloat) -1)) {
		gfloat _tmp1_;
		_tmp1_ = sdx_graphics_nine_patch_GetBottomHeight (self);
		result = _tmp1_;
		return result;
	}
	_tmp2_ = self->padBottom;
	result = _tmp2_;
	return result;
}


/** 
         * See link #setPadding(float, float, float, float) 
         */
void sdx_graphics_nine_patch_SetPadBottom (SdxGraphicsNinePatch* self, gfloat bottom) {
	gfloat _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = bottom;
	self->padBottom = _tmp0_;
}


/** 
         * Multiplies the top/left/bottom/right sizes and padding by the specified amount. 
         */
void sdx_graphics_nine_patch_Scale (SdxGraphicsNinePatch* self, gfloat scaleX, gfloat scaleY) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	gfloat _tmp6_;
	gfloat _tmp7_;
	gfloat _tmp8_;
	gfloat _tmp9_;
	gfloat _tmp10_;
	gfloat _tmp11_;
	gfloat _tmp12_;
	gfloat _tmp15_;
	gfloat _tmp18_;
	gfloat _tmp21_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->leftWidth;
	_tmp1_ = scaleX;
	self->leftWidth = _tmp0_ * _tmp1_;
	_tmp2_ = self->rightWidth;
	_tmp3_ = scaleX;
	self->rightWidth = _tmp2_ * _tmp3_;
	_tmp4_ = self->topHeight;
	_tmp5_ = scaleY;
	self->topHeight = _tmp4_ * _tmp5_;
	_tmp6_ = self->bottomHeight;
	_tmp7_ = scaleY;
	self->bottomHeight = _tmp6_ * _tmp7_;
	_tmp8_ = self->middleWidth;
	_tmp9_ = scaleX;
	self->middleWidth = _tmp8_ * _tmp9_;
	_tmp10_ = self->middleHeight;
	_tmp11_ = scaleY;
	self->middleHeight = _tmp10_ * _tmp11_;
	_tmp12_ = self->padLeft;
	if (_tmp12_ != ((gfloat) -1)) {
		gfloat _tmp13_;
		gfloat _tmp14_;
		_tmp13_ = self->padLeft;
		_tmp14_ = scaleX;
		self->padLeft = _tmp13_ * _tmp14_;
	}
	_tmp15_ = self->padRight;
	if (_tmp15_ != ((gfloat) -1)) {
		gfloat _tmp16_;
		gfloat _tmp17_;
		_tmp16_ = self->padRight;
		_tmp17_ = scaleX;
		self->padRight = _tmp16_ * _tmp17_;
	}
	_tmp18_ = self->padTop;
	if (_tmp18_ != ((gfloat) -1)) {
		gfloat _tmp19_;
		gfloat _tmp20_;
		_tmp19_ = self->padTop;
		_tmp20_ = scaleY;
		self->padTop = _tmp19_ * _tmp20_;
	}
	_tmp21_ = self->padBottom;
	if (_tmp21_ != ((gfloat) -1)) {
		gfloat _tmp22_;
		gfloat _tmp23_;
		_tmp22_ = self->padBottom;
		_tmp23_ = scaleY;
		self->padBottom = _tmp22_ * _tmp23_;
	}
}


static void sdx_graphics_nine_patch_instance_init (SdxGraphicsNinePatch * self) {
	self->ref_count = 1;
	self->bottomLeft = -1;
	self->bottomCenter = -1;
	self->bottomRight = -1;
	self->middleLeft = -1;
	self->middleCenter = -1;
	self->middleRight = -1;
	self->topLeft = -1;
	self->topCenter = -1;
	self->topRight = -1;
	self->color = SDX_COLOR_White;
	self->padLeft = (gfloat) -1;
	self->padRight = (gfloat) -1;
	self->padTop = (gfloat) -1;
	self->padBottom = (gfloat) -1;
}


void sdx_graphics_nine_patch_free (SdxGraphicsNinePatch * self) {
	_sdx_graphics_surface_release0 (self->texture);
	g_slice_free (SdxGraphicsNinePatch, self);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}




