/** updated by adriac */
/* TextureRegion.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from TextureRegion.vala, do not modify */

/*[Adriac:Sdx.Graphics:TextureRegion:FromRegion:SdxGraphicsTextureRegionFromRegion:sdx_graphics_texture_region_fromregion]*/
/*[Adriac:Sdx.Graphics:TextureRegion:FromTexture:SdxGraphicsTextureRegionFromTexture:sdx_graphics_texture_region_fromtexture]*/
/*[Adriac:Sdx.Graphics::TextureRegion:SdxGraphicsTextureRegion:sdx_graphics_texture_region]*/
/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

typedef struct _SdxGraphicsTextureRegion SdxGraphicsTextureRegion;
typedef struct _SdxGraphicsSurface SdxGraphicsSurface;
typedef SdxGraphicsSurface SdxGraphicsSurfaceTextureSurface;
// symtbl.1 sdx_graphics_surface
void sdx_graphics_surface_release (SdxGraphicsSurface* self);
void sdx_graphics_surface_free (SdxGraphicsSurface* self);
SdxGraphicsSurface* sdx_graphics_surface_retain (SdxGraphicsSurface* self);
#define _sdx_graphics_surface_release0(var) ((var == NULL) ? NULL : (var = (sdx_graphics_surface_release (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef SdxGraphicsTextureRegion SdxGraphicsTextureRegionFromTexture;
typedef SdxGraphicsTextureRegion SdxGraphicsTextureRegionFromRegion;

struct _SdxGraphicsTextureRegion {
	gint ref_count;
	SdxGraphicsSurfaceTextureSurface* texture;
	gint top;
	gint left;
	gint width;
	gint height;
	gint regionWidth;
	gint regionHeight;
	gfloat u;
	gfloat v;
	gfloat u2;
	gfloat v2;
	gint index;
	gchar* name;
	gint offsetX;
	gint offsetY;
	gint packedWidth;
	gint packedHeight;
	gint originalWidth;
	gint originalHeight;
	gboolean rotate;
	gint* splits;
	gint splits_length1;
	gint* pads;
	gint pads_length1;
};



void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion * self);
void sdx_graphics_surface_free (SdxGraphicsSurface * self);
static void sdx_graphics_texture_region_instance_init (SdxGraphicsTextureRegion * self);
SdxGraphicsTextureRegion* sdx_graphics_texture_region_retain (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_release (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetRegion (SdxGraphicsTextureRegion* self, gfloat u, gfloat v, gfloat u2, gfloat v2);
void sdx_graphics_texture_region_SetRegionXY (SdxGraphicsTextureRegion* self, gint x, gint y, gint width, gint height);
void sdx_graphics_texture_region_SetByRegion (SdxGraphicsTextureRegion* self, SdxGraphicsTextureRegion* region);
void sdx_graphics_texture_region_SetByRegionXY (SdxGraphicsTextureRegion* self, SdxGraphicsTextureRegion* region, gint x, gint y, gint width, gint height);
gint sdx_graphics_texture_region_GetRegionX (SdxGraphicsTextureRegion* self);
gint sdx_graphics_texture_region_GetRegionY (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_Flip (SdxGraphicsTextureRegion* self, gboolean x, gboolean y);
gfloat sdx_graphics_texture_region_GetU (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetU (SdxGraphicsTextureRegion* self, gfloat u);
gfloat sdx_graphics_texture_region_GetV (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetV (SdxGraphicsTextureRegion* self, gfloat v);
gfloat sdx_graphics_texture_region_GetU2 (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetU2 (SdxGraphicsTextureRegion* self, gfloat u2);
gfloat sdx_graphics_texture_region_GetV2 (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetV2 (SdxGraphicsTextureRegion* self, gfloat v2);
void sdx_graphics_texture_region_SetRegionX (SdxGraphicsTextureRegion* self, gint x);
void sdx_graphics_texture_region_SetRegionY (SdxGraphicsTextureRegion* self, gint y);
gint sdx_graphics_texture_region_GetRegionWidth (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetRegionWidth (SdxGraphicsTextureRegion* self, gint width);
gboolean sdx_graphics_texture_region_IsFlipX (SdxGraphicsTextureRegion* self);
gint sdx_graphics_texture_region_GetRegionHeight (SdxGraphicsTextureRegion* self);
void sdx_graphics_texture_region_SetRegionHeight (SdxGraphicsTextureRegion* self, gint height);
gboolean sdx_graphics_texture_region_IsFlipY (SdxGraphicsTextureRegion* self);
SdxGraphicsTextureRegion* sdx_graphics_texture_region_new (void);
SdxGraphicsTextureRegionFromTexture* sdx_graphics_texture_region_from_texture_new (SdxGraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height);
gint sdx_graphics_surface_get_width (SdxGraphicsSurface* self);
gint sdx_graphics_surface_get_height (SdxGraphicsSurface* self);
SdxGraphicsTextureRegionFromRegion* sdx_graphics_texture_region_from_region_new (SdxGraphicsTextureRegion* region, gint x, gint y, gint width, gint height);


SdxGraphicsTextureRegion* sdx_graphics_texture_region_retain (SdxGraphicsTextureRegion* self) {
	SdxGraphicsTextureRegion* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_atomic_int_add ((volatile gint *) (&self->ref_count), 1);
	result = self;
	return result;
}


void sdx_graphics_texture_region_release (SdxGraphicsTextureRegion* self) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_atomic_int_dec_and_test ((volatile gint *) (&self->ref_count));
	if (_tmp0_) {
		sdx_graphics_texture_region_free (self);
	}
}


void sdx_graphics_texture_region_SetRegion (SdxGraphicsTextureRegion* self, gfloat u, gfloat v, gfloat u2, gfloat v2) {
	gint texWidth = 0;
	gint _tmp0_;
	gint texHeight = 0;
	gint _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gdouble _tmp4_;
	gint _tmp5_;
	gdouble _tmp6_;
	gfloat _tmp7_;
	gfloat _tmp8_;
	gdouble _tmp9_;
	gint _tmp10_;
	gdouble _tmp11_;
	gboolean _tmp12_ = FALSE;
	gint _tmp13_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->width;
	texWidth = _tmp0_;
	_tmp1_ = self->height;
	texHeight = _tmp1_;
	_tmp2_ = u2;
	_tmp3_ = u;
	_tmp4_ = fabs ((gdouble) (_tmp2_ - _tmp3_));
	_tmp5_ = texWidth;
	_tmp6_ = round (_tmp4_ * _tmp5_);
	self->regionWidth = (gint) _tmp6_;
	_tmp7_ = v2;
	_tmp8_ = v;
	_tmp9_ = fabs ((gdouble) (_tmp7_ - _tmp8_));
	_tmp10_ = texHeight;
	_tmp11_ = round (_tmp9_ * _tmp10_);
	self->regionHeight = (gint) _tmp11_;
	_tmp13_ = self->regionWidth;
	if (_tmp13_ == 1) {
		gint _tmp14_;
		_tmp14_ = self->regionHeight;
		_tmp12_ = _tmp14_ == 1;
	} else {
		_tmp12_ = FALSE;
	}
	if (_tmp12_) {
		gfloat adjustX = 0.0F;
		gint _tmp15_;
		gfloat _tmp16_;
		gfloat _tmp17_;
		gfloat adjustY = 0.0F;
		gint _tmp18_;
		gfloat _tmp19_;
		gfloat _tmp20_;
		_tmp15_ = texWidth;
		adjustX = 0.25f / _tmp15_;
		_tmp16_ = adjustX;
		u = _tmp16_;
		_tmp17_ = adjustX;
		u2 = _tmp17_;
		_tmp18_ = texHeight;
		adjustY = 0.25f / _tmp18_;
		_tmp19_ = adjustY;
		v = _tmp19_;
		_tmp20_ = adjustY;
		v2 = _tmp20_;
	}
}


void sdx_graphics_texture_region_SetRegionXY (SdxGraphicsTextureRegion* self, gint x, gint y, gint width, gint height) {
	gint invTexWidth = 0;
	gint _tmp0_;
	gint invTexHeight = 0;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gdouble _tmp9_;
	gint _tmp10_;
	gdouble _tmp11_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->width;
	invTexWidth = 1 / _tmp0_;
	_tmp1_ = self->height;
	invTexHeight = 1 / _tmp1_;
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_ = x;
	_tmp5_ = width;
	_tmp6_ = y;
	_tmp7_ = height;
	sdx_graphics_texture_region_SetRegion (self, (gfloat) (_tmp2_ * invTexWidth), (gfloat) (_tmp3_ * invTexHeight), (gfloat) ((_tmp4_ + _tmp5_) * invTexWidth), (gfloat) ((_tmp6_ + _tmp7_) * invTexHeight));
	_tmp8_ = width;
	_tmp9_ = fabs ((gdouble) _tmp8_);
	self->regionWidth = (gint) _tmp9_;
	_tmp10_ = height;
	_tmp11_ = fabs ((gdouble) _tmp10_);
	self->regionHeight = (gint) _tmp11_;
}


static gpointer _sdx_graphics_surface_retain0 (gpointer self) {
	return self ? sdx_graphics_surface_retain (self) : NULL;
}


void sdx_graphics_texture_region_SetByRegion (SdxGraphicsTextureRegion* self, SdxGraphicsTextureRegion* region) {
	SdxGraphicsTextureRegion* _tmp0_;
	SdxGraphicsSurfaceTextureSurface* _tmp1_;
	SdxGraphicsSurfaceTextureSurface* _tmp2_;
	SdxGraphicsTextureRegion* _tmp3_;
	gfloat _tmp4_;
	SdxGraphicsTextureRegion* _tmp5_;
	gfloat _tmp6_;
	SdxGraphicsTextureRegion* _tmp7_;
	gfloat _tmp8_;
	SdxGraphicsTextureRegion* _tmp9_;
	gfloat _tmp10_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (region != NULL);
	_tmp0_ = region;
	_tmp1_ = _tmp0_->texture;
	_tmp2_ = _sdx_graphics_surface_retain0 (_tmp1_);
	_sdx_graphics_surface_release0 (self->texture);
	self->texture = _tmp2_;
	_tmp3_ = region;
	_tmp4_ = _tmp3_->u;
	_tmp5_ = region;
	_tmp6_ = _tmp5_->v;
	_tmp7_ = region;
	_tmp8_ = _tmp7_->u2;
	_tmp9_ = region;
	_tmp10_ = _tmp9_->v2;
	sdx_graphics_texture_region_SetRegion (self, _tmp4_, _tmp6_, _tmp8_, _tmp10_);
}


void sdx_graphics_texture_region_SetByRegionXY (SdxGraphicsTextureRegion* self, SdxGraphicsTextureRegion* region, gint x, gint y, gint width, gint height) {
	SdxGraphicsTextureRegion* _tmp0_;
	SdxGraphicsSurfaceTextureSurface* _tmp1_;
	SdxGraphicsSurfaceTextureSurface* _tmp2_;
	SdxGraphicsTextureRegion* _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	SdxGraphicsTextureRegion* _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	gint _tmp10_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (region != NULL);
	_tmp0_ = region;
	_tmp1_ = _tmp0_->texture;
	_tmp2_ = _sdx_graphics_surface_retain0 (_tmp1_);
	_sdx_graphics_surface_release0 (self->texture);
	self->texture = _tmp2_;
	_tmp3_ = region;
	_tmp4_ = sdx_graphics_texture_region_GetRegionX (_tmp3_);
	_tmp5_ = x;
	_tmp6_ = region;
	_tmp7_ = sdx_graphics_texture_region_GetRegionY (_tmp6_);
	_tmp8_ = y;
	_tmp9_ = width;
	_tmp10_ = height;
	sdx_graphics_texture_region_SetRegionXY (self, _tmp4_ + _tmp5_, _tmp7_ + _tmp8_, _tmp9_, _tmp10_);
}


void sdx_graphics_texture_region_Flip (SdxGraphicsTextureRegion* self, gboolean x, gboolean y) {
	gboolean _tmp0_;
	gboolean _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp0_ = x;
	if (_tmp0_) {
		gfloat temp = 0.0F;
		gfloat _tmp1_;
		gfloat _tmp2_;
		gfloat _tmp3_;
		_tmp1_ = self->u;
		temp = _tmp1_;
		_tmp2_ = self->u2;
		self->u = _tmp2_;
		_tmp3_ = temp;
		self->u2 = _tmp3_;
	}
	_tmp4_ = y;
	if (_tmp4_) {
		gfloat temp = 0.0F;
		gfloat _tmp5_;
		gfloat _tmp6_;
		gfloat _tmp7_;
		_tmp5_ = self->v;
		temp = _tmp5_;
		_tmp6_ = self->v2;
		self->v = _tmp6_;
		_tmp7_ = temp;
		self->v2 = _tmp7_;
	}
}


gfloat sdx_graphics_texture_region_GetU (SdxGraphicsTextureRegion* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->u;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_SetU (SdxGraphicsTextureRegion* self, gfloat u) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gdouble _tmp3_;
	gint _tmp4_;
	gdouble _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = u;
	self->u = _tmp0_;
	_tmp1_ = self->u2;
	_tmp2_ = u;
	_tmp3_ = fabs ((gdouble) (_tmp1_ - _tmp2_));
	_tmp4_ = self->width;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionWidth = (gint) _tmp5_;
}


gfloat sdx_graphics_texture_region_GetV (SdxGraphicsTextureRegion* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->v;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_SetV (SdxGraphicsTextureRegion* self, gfloat v) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gdouble _tmp3_;
	gint _tmp4_;
	gdouble _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = v;
	self->v = _tmp0_;
	_tmp1_ = self->v2;
	_tmp2_ = v;
	_tmp3_ = fabs ((gdouble) (_tmp1_ - _tmp2_));
	_tmp4_ = self->height;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionHeight = (gint) _tmp5_;
}


gfloat sdx_graphics_texture_region_GetU2 (SdxGraphicsTextureRegion* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->u2;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_SetU2 (SdxGraphicsTextureRegion* self, gfloat u2) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gdouble _tmp3_;
	gint _tmp4_;
	gdouble _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = u2;
	self->u2 = _tmp0_;
	_tmp1_ = u2;
	_tmp2_ = self->u;
	_tmp3_ = fabs ((gdouble) (_tmp1_ - _tmp2_));
	_tmp4_ = self->width;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionWidth = (gint) _tmp5_;
}


gfloat sdx_graphics_texture_region_GetV2 (SdxGraphicsTextureRegion* self) {
	gfloat result = 0.0F;
	gfloat _tmp0_;
	g_return_val_if_fail (self != NULL, 0.0F);
	_tmp0_ = self->v2;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_SetV2 (SdxGraphicsTextureRegion* self, gfloat v2) {
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gdouble _tmp3_;
	gint _tmp4_;
	gdouble _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = v2;
	self->v2 = _tmp0_;
	_tmp1_ = v2;
	_tmp2_ = self->v;
	_tmp3_ = fabs ((gdouble) (_tmp1_ - _tmp2_));
	_tmp4_ = self->height;
	_tmp5_ = round (_tmp3_ * _tmp4_);
	self->regionHeight = (gint) _tmp5_;
}


gint sdx_graphics_texture_region_GetRegionX (SdxGraphicsTextureRegion* self) {
	gint result = 0;
	gfloat _tmp0_;
	gint _tmp1_;
	gdouble _tmp2_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->u;
	_tmp1_ = self->width;
	_tmp2_ = round ((gdouble) (_tmp0_ * _tmp1_));
	result = (gint) _tmp2_;
	return result;
}


void sdx_graphics_texture_region_SetRegionX (SdxGraphicsTextureRegion* self, gint x) {
	gint _tmp0_;
	gint _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = x;
	_tmp1_ = self->width;
	sdx_graphics_texture_region_SetU (self, _tmp0_ / ((gfloat) _tmp1_));
}


gint sdx_graphics_texture_region_GetRegionY (SdxGraphicsTextureRegion* self) {
	gint result = 0;
	gfloat _tmp0_;
	gint _tmp1_;
	gdouble _tmp2_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->v;
	_tmp1_ = self->height;
	_tmp2_ = round ((gdouble) (_tmp0_ * _tmp1_));
	result = (gint) _tmp2_;
	return result;
}


void sdx_graphics_texture_region_SetRegionY (SdxGraphicsTextureRegion* self, gint y) {
	gint _tmp0_;
	gint _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = y;
	_tmp1_ = self->height;
	sdx_graphics_texture_region_SetV (self, (gfloat) (_tmp0_ / _tmp1_));
}


/** 
         * Returns the region's width. 
         */
gint sdx_graphics_texture_region_GetRegionWidth (SdxGraphicsTextureRegion* self) {
	gint result = 0;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->regionWidth;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_SetRegionWidth (SdxGraphicsTextureRegion* self, gint width) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = sdx_graphics_texture_region_IsFlipX (self);
	if (_tmp0_) {
		gfloat _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		_tmp1_ = self->u2;
		_tmp2_ = width;
		_tmp3_ = self->width;
		sdx_graphics_texture_region_SetU (self, _tmp1_ + (_tmp2_ / ((gfloat) _tmp3_)));
	} else {
		gfloat _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		_tmp4_ = self->u;
		_tmp5_ = width;
		_tmp6_ = self->width;
		sdx_graphics_texture_region_SetU2 (self, _tmp4_ + (_tmp5_ / ((gfloat) _tmp6_)));
	}
}


/** 
         * Returns the region's height. 
         */
gint sdx_graphics_texture_region_GetRegionHeight (SdxGraphicsTextureRegion* self) {
	gint result = 0;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->regionHeight;
	result = _tmp0_;
	return result;
}


void sdx_graphics_texture_region_SetRegionHeight (SdxGraphicsTextureRegion* self, gint height) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = sdx_graphics_texture_region_IsFlipY (self);
	if (_tmp0_) {
		gfloat _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		_tmp1_ = self->v2;
		_tmp2_ = height;
		_tmp3_ = self->height;
		sdx_graphics_texture_region_SetV (self, _tmp1_ + (_tmp2_ / ((gfloat) _tmp3_)));
	} else {
		gfloat _tmp4_;
		gint _tmp5_;
		gint _tmp6_;
		_tmp4_ = self->v;
		_tmp5_ = height;
		_tmp6_ = self->height;
		sdx_graphics_texture_region_SetV2 (self, _tmp4_ + (_tmp5_ / ((gfloat) _tmp6_)));
	}
}


gboolean sdx_graphics_texture_region_IsFlipX (SdxGraphicsTextureRegion* self) {
	gboolean result = FALSE;
	gfloat _tmp0_;
	gfloat _tmp1_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->u;
	_tmp1_ = self->u2;
	result = _tmp0_ > _tmp1_;
	return result;
}


gboolean sdx_graphics_texture_region_IsFlipY (SdxGraphicsTextureRegion* self) {
	gboolean result = FALSE;
	gfloat _tmp0_;
	gfloat _tmp1_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->v;
	_tmp1_ = self->v2;
	result = _tmp0_ > _tmp1_;
	return result;
}


SdxGraphicsTextureRegion* sdx_graphics_texture_region_new (void) {
	SdxGraphicsTextureRegion* self;
	self = g_slice_new0 (SdxGraphicsTextureRegion);
	sdx_graphics_texture_region_instance_init (self);
	return self;
}


SdxGraphicsTextureRegionFromTexture* sdx_graphics_texture_region_from_texture_new (SdxGraphicsSurfaceTextureSurface* texture, gint x, gint y, gint width, gint height) {
	SdxGraphicsTextureRegionFromTexture* self;
	gint _tmp0_ = 0;
	gint _tmp1_;
	gint _tmp6_ = 0;
	gint _tmp7_;
	SdxGraphicsSurfaceTextureSurface* _tmp12_;
	SdxGraphicsSurfaceTextureSurface* _tmp13_;
	gint _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	gint _tmp19_;
	gint _tmp20_;
	gint _tmp21_;
	g_return_val_if_fail (texture != NULL, NULL);
	self = (SdxGraphicsTextureRegionFromTexture*) sdx_graphics_texture_region_new ();
	_tmp1_ = width;
	if (_tmp1_ == 0) {
		SdxGraphicsSurfaceTextureSurface* _tmp2_;
		gint _tmp3_;
		gint _tmp4_;
		_tmp2_ = texture;
		_tmp3_ = sdx_graphics_surface_get_width ((SdxGraphicsSurface*) _tmp2_);
		_tmp4_ = _tmp3_;
		_tmp0_ = _tmp4_;
	} else {
		gint _tmp5_;
		_tmp5_ = width;
		_tmp0_ = _tmp5_;
	}
	width = _tmp0_;
	_tmp7_ = height;
	if (_tmp7_ == 0) {
		SdxGraphicsSurfaceTextureSurface* _tmp8_;
		gint _tmp9_;
		gint _tmp10_;
		_tmp8_ = texture;
		_tmp9_ = sdx_graphics_surface_get_height ((SdxGraphicsSurface*) _tmp8_);
		_tmp10_ = _tmp9_;
		_tmp6_ = _tmp10_;
	} else {
		gint _tmp11_;
		_tmp11_ = height;
		_tmp6_ = _tmp11_;
	}
	height = _tmp6_;
	_tmp12_ = texture;
	_tmp13_ = _sdx_graphics_surface_retain0 (_tmp12_);
	_sdx_graphics_surface_release0 (((SdxGraphicsTextureRegion*) self)->texture);
	((SdxGraphicsTextureRegion*) self)->texture = _tmp13_;
	_tmp14_ = x;
	((SdxGraphicsTextureRegion*) self)->top = _tmp14_;
	_tmp15_ = y;
	((SdxGraphicsTextureRegion*) self)->left = _tmp15_;
	_tmp16_ = width;
	((SdxGraphicsTextureRegion*) self)->width = _tmp16_;
	_tmp17_ = height;
	((SdxGraphicsTextureRegion*) self)->height = _tmp17_;
	_tmp18_ = x;
	_tmp19_ = y;
	_tmp20_ = width;
	_tmp21_ = height;
	sdx_graphics_texture_region_SetRegionXY ((SdxGraphicsTextureRegion*) self, _tmp18_, _tmp19_, _tmp20_, _tmp21_);
	return self;
}


SdxGraphicsTextureRegionFromRegion* sdx_graphics_texture_region_from_region_new (SdxGraphicsTextureRegion* region, gint x, gint y, gint width, gint height) {
	SdxGraphicsTextureRegionFromRegion* self;
	gint _tmp0_ = 0;
	gint _tmp1_;
	gint _tmp7_ = 0;
	gint _tmp8_;
	SdxGraphicsTextureRegion* _tmp14_;
	SdxGraphicsSurfaceTextureSurface* _tmp15_;
	SdxGraphicsSurfaceTextureSurface* _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	gint _tmp19_;
	gint _tmp20_;
	SdxGraphicsTextureRegion* _tmp21_;
	gint _tmp22_;
	gint _tmp23_;
	SdxGraphicsTextureRegion* _tmp24_;
	gint _tmp25_;
	gint _tmp26_;
	gint _tmp27_;
	gint _tmp28_;
	g_return_val_if_fail (region != NULL, NULL);
	self = (SdxGraphicsTextureRegionFromRegion*) sdx_graphics_texture_region_new ();
	_tmp1_ = width;
	if (_tmp1_ == 0) {
		SdxGraphicsTextureRegion* _tmp2_;
		SdxGraphicsSurfaceTextureSurface* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
		_tmp2_ = region;
		_tmp3_ = _tmp2_->texture;
		_tmp4_ = sdx_graphics_surface_get_width ((SdxGraphicsSurface*) _tmp3_);
		_tmp5_ = _tmp4_;
		_tmp0_ = _tmp5_;
	} else {
		gint _tmp6_;
		_tmp6_ = width;
		_tmp0_ = _tmp6_;
	}
	width = _tmp0_;
	_tmp8_ = height;
	if (_tmp8_ == 0) {
		SdxGraphicsTextureRegion* _tmp9_;
		SdxGraphicsSurfaceTextureSurface* _tmp10_;
		gint _tmp11_;
		gint _tmp12_;
		_tmp9_ = region;
		_tmp10_ = _tmp9_->texture;
		_tmp11_ = sdx_graphics_surface_get_height ((SdxGraphicsSurface*) _tmp10_);
		_tmp12_ = _tmp11_;
		_tmp7_ = _tmp12_;
	} else {
		gint _tmp13_;
		_tmp13_ = height;
		_tmp7_ = _tmp13_;
	}
	height = _tmp7_;
	_tmp14_ = region;
	_tmp15_ = _tmp14_->texture;
	_tmp16_ = _sdx_graphics_surface_retain0 (_tmp15_);
	_sdx_graphics_surface_release0 (((SdxGraphicsTextureRegion*) self)->texture);
	((SdxGraphicsTextureRegion*) self)->texture = _tmp16_;
	_tmp17_ = x;
	((SdxGraphicsTextureRegion*) self)->top = _tmp17_;
	_tmp18_ = y;
	((SdxGraphicsTextureRegion*) self)->left = _tmp18_;
	_tmp19_ = width;
	((SdxGraphicsTextureRegion*) self)->width = _tmp19_;
	_tmp20_ = height;
	((SdxGraphicsTextureRegion*) self)->height = _tmp20_;
	_tmp21_ = region;
	_tmp22_ = sdx_graphics_texture_region_GetRegionX (_tmp21_);
	_tmp23_ = x;
	_tmp24_ = region;
	_tmp25_ = sdx_graphics_texture_region_GetRegionY (_tmp24_);
	_tmp26_ = y;
	_tmp27_ = width;
	_tmp28_ = height;
	sdx_graphics_texture_region_SetRegionXY ((SdxGraphicsTextureRegion*) self, _tmp22_ + _tmp23_, _tmp25_ + _tmp26_, _tmp27_, _tmp28_);
	return self;
}


static void sdx_graphics_texture_region_instance_init (SdxGraphicsTextureRegion * self) {
	self->ref_count = 1;
}


void sdx_graphics_texture_region_free (SdxGraphicsTextureRegion * self) {
	_sdx_graphics_surface_release0 (self->texture);
	_g_free0 (self->name);
	self->splits = (g_free (self->splits), NULL);
	self->pads = (g_free (self->pads), NULL);
	g_slice_free (SdxGraphicsTextureRegion, self);
}




