/** updated by adriac */
/* Config.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTANTS_DATADIR ""
#define CONSTANTS_PKGDATADIR ""
#define CONSTANTS_GETTEXT_PACKAGE ""
#define CONSTANTS_RELEASE_NAME ""
#define CONSTANTS_VERSION ""




