/** updated by adriac */
/* Game.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from Game.vala, do not modify */

/*[Adriac:::Game:Game:game]*/

#include <glib.h>
#include <glib-object.h>
#include <SDL_video.h>
#include <SDL_rect.h>
#include <SDL_pixels.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>

typedef struct _SdxAbstractGame SdxAbstractGame;
typedef SdxAbstractGame Game;
typedef struct _SdxUiComponent SdxUiComponent;
typedef SdxUiComponent SdxUiWindow;
typedef struct _EntitasWorld EntitasWorld;
typedef EntitasWorld Factory;
typedef SdxUiComponent SdxUiLabel;
typedef SdxUiLabel SdxUiLabelText;
typedef SdxUiComponent SdxUiButton;
typedef SdxUiButton SdxUiButtonNinePatch;
// symtbl.1 sdx_ui_component
void sdx_ui_component_release (SdxUiComponent* self);
void sdx_ui_component_free (SdxUiComponent* self);
SdxUiComponent* sdx_ui_component_retain (SdxUiComponent* self);
#define _sdx_ui_component_release0(var) ((var == NULL) ? NULL : (var = (sdx_ui_component_release (var), NULL)))
typedef struct _Block26Data Block26Data;
// symtbl.1 entitas_world
void entitas_world_release (EntitasWorld* self);
void entitas_world_free (EntitasWorld* self);
EntitasWorld* entitas_world_retain (EntitasWorld* self);
#define _entitas_world_release0(var) ((var == NULL) ? NULL : (var = (entitas_world_release (var), NULL)))
// symtbl.1 sdx_abstract_game
void sdx_abstract_game_release (SdxAbstractGame* self);
void sdx_abstract_game_free (SdxAbstractGame* self);
SdxAbstractGame* sdx_abstract_game_retain (SdxAbstractGame* self);
#define _sdx_abstract_game_release0(var) ((var == NULL) ? NULL : (var = (sdx_abstract_game_release (var), NULL)))

#define SDX_UI_COMPONENT_TYPE_KIND (sdx_ui_component_kind_get_type ())
typedef struct _SdxFont SdxFont;
typedef struct _SdxGraphicsSprite SdxGraphicsSprite;
typedef struct _SdxInputProcessor SdxInputProcessor;
typedef struct _SystemsDisplaySystem SystemsDisplaySystem;
typedef struct _EntitasSystem EntitasSystem;
typedef EntitasSystem SystemsSpawnSystem;
typedef EntitasSystem SystemsInputSystem;
typedef EntitasSystem SystemsPhysicsSystem;
typedef EntitasSystem SystemsCollisionSystem;
typedef EntitasSystem SystemsAnimationSystem;
typedef EntitasSystem SystemsExpireSystem;
typedef EntitasSystem SystemsSoundSystem;
typedef EntitasSystem SystemsScoreSystem;
// symtbl.1 entitas_system
void entitas_system_release (EntitasSystem* self);
void entitas_system_free (EntitasSystem* self);
EntitasSystem* entitas_system_retain (EntitasSystem* self);
#define _entitas_system_release0(var) ((var == NULL) ? NULL : (var = (entitas_system_release (var), NULL)))
// symtbl.1 systems_display_system
void systems_display_system_release (SystemsDisplaySystem* self);
void systems_display_system_free (SystemsDisplaySystem* self);
SystemsDisplaySystem* systems_display_system_retain (SystemsDisplaySystem* self);
#define _systems_display_system_release0(var) ((var == NULL) ? NULL : (var = (systems_display_system_release (var), NULL)))

typedef void (*SdxAbstractGameAbstractUpdate) (void* user_data);
typedef void (*SdxAbstractGameAbstractDraw) (void* user_data);
struct _SdxAbstractGame {
	gint ref_count;
	gint width;
	gint height;
	SdxAbstractGameAbstractUpdate Update;
	gpointer Update_target;
	GDestroyNotify Update_target_destroy_notify;
	SdxAbstractGameAbstractDraw Draw;
	gpointer Draw_target;
	GDestroyNotify Draw_target_destroy_notify;
};

struct _Block26Data {
	int _ref_count_;
	Game* self;
	Factory* world;
	SdxUiLabelText* label;
	SdxUiButtonNinePatch* button;
	SdxUiWindow* window;
};

typedef enum  {
	SDX_UI_COMPONENT_KIND_Window,
	SDX_UI_COMPONENT_KIND_Label,
	SDX_UI_COMPONENT_KIND_Button
} SdxUiComponentKind;

typedef void (*SdxUiComponentComponentOnMouseClick) (SdxUiComponent* c, gint x, gint y, void* user_data);
typedef void (*SdxUiComponentComponentOnMouseEnter) (SdxUiComponent* c, gint x, gint y, void* user_data);
typedef void (*SdxUiComponentComponentOnMouseLeave) (SdxUiComponent* c, gint x, gint y, void* user_data);
typedef void (*SdxUiComponentComponentStart) (void* user_data);
struct _SdxUiComponent {
	gint ref_count;
	SdxUiComponentKind kind;
	SdxUiComponent* parent;
	SDL_Window* root;
	SDL_Rect* bounds;
	SDL_Color* foreground;
	SDL_Color* background;
	SdxFont* font;
	gboolean visible;
	gboolean enabled;
	gboolean valid;
	gchar* name;
	gboolean focus;
	gboolean selected;
	gchar* text;
	GList* controls;
	SdxGraphicsSprite** image;
	gint image_length1;
	gint index;
	SdxInputProcessor* handler;
	SdxUiComponentComponentOnMouseClick OnMouseClick;
	gpointer OnMouseClick_target;
	GDestroyNotify OnMouseClick_target_destroy_notify;
	SdxUiComponentComponentOnMouseEnter OnMouseEnter;
	gpointer OnMouseEnter_target;
	GDestroyNotify OnMouseEnter_target_destroy_notify;
	SdxUiComponentComponentOnMouseLeave OnMouseLeave;
	gpointer OnMouseLeave_target;
	GDestroyNotify OnMouseLeave_target_destroy_notify;
	SdxUiComponentComponentStart Start;
	gpointer Start_target;
	GDestroyNotify Start_target_destroy_notify;
	SdxUiComponentComponentStart Stop;
	gpointer Stop_target;
	GDestroyNotify Stop_target_destroy_notify;
};


extern SdxFont* sdx_largeFont;
extern gfloat sdx_delta;

void sdx_abstract_game_free (SdxAbstractGame * self);
void sdx_ui_component_free (SdxUiComponent * self);
Game* game_new (SdxUiWindow* window);
void entitas_world_free (EntitasWorld * self);
static Block26Data* block26_data_ref (Block26Data* _data26_);
static void block26_data_unref (void * _userdata_);
SdxAbstractGame* sdx_abstract_game_new (void);
GType sdx_ui_component_kind_get_type (void) G_GNUC_CONST;
void sdx_font_free (SdxFont * self);
void sdx_graphics_sprite_free (SdxGraphicsSprite * self);
void sdx_input_processor_free (SdxInputProcessor * self);
void sdx_SetResourceBase (const gchar* path);
void sdx_SetSmallFont (const gchar* path, gint size);
void sdx_SetDefaultFont (const gchar* path, gint size);
void sdx_SetLargeFont (const gchar* path, gint size);
void sdx_SetAtlas (const gchar* path);
Factory* factory_new (void);
SdxUiLabelText* sdx_ui_label_text_new (const gchar* text, SdxFont* font, SDL_Color fg, SDL_Color* bg);
SdxUiButtonNinePatch* sdx_ui_button_nine_patch_new (const gchar* text, SdxFont* font, SDL_Color fg, const gchar* img, const gchar* alt);
void sdx_ui_component_Add (SdxUiComponent* self, SdxUiComponent* child);
SdxUiComponent* sdx_ui_component_SetPos (SdxUiComponent* self, gint x, gint y);
gint sdx_ui_component_get_width (SdxUiComponent* self);
static void __lambda111_ (Block26Data* _data26_, SdxUiComponent* c, gint x, gint y);
void sdx_ui_component_Remove (SdxUiComponent* self, SdxUiComponent* child);
void factory_AddPlayer (Factory* self, gint x, gint y);
static void __lambda112_ (Block26Data* _data26_);
void entitas_world_Execute (EntitasWorld* self, gfloat delta);
static void ___lambda112__sdx_abstract_game_abstract_update (gpointer self);
static void ___lambda111__sdx_ui_component_component_on_mouse_click (SdxUiComponent* c, gint x, gint y, gpointer self);
void systems_display_system_free (SystemsDisplaySystem * self);
SystemsDisplaySystem* systems_display_system_new (Game* game, Factory* world);
void entitas_system_free (EntitasSystem * self);
EntitasWorld* entitas_world_AddSystem (EntitasWorld* self, EntitasSystem* system);
SystemsSpawnSystem* systems_spawn_system_new (Game* game, Factory* world);
SystemsInputSystem* systems_input_system_new (Game* game, Factory* world);
SystemsPhysicsSystem* systems_physics_system_new (Game* game, Factory* world);
SystemsCollisionSystem* systems_collision_system_new (Game* game, Factory* world);
SystemsAnimationSystem* systems_animation_system_new (Game* game, Factory* world);
SystemsExpireSystem* systems_expire_system_new (Game* game, Factory* world);
SystemsSoundSystem* systems_sound_system_new (Game* game, Factory* world);
SystemsScoreSystem* systems_score_system_new (Game* game, Factory* world);
void entitas_world_Initialize (EntitasWorld* self);
void factory_AddBackground (Factory* self, gint x, gint y);

extern const SDL_Color SDX_COLOR_NavajoWhite;
extern const SDL_Color SDX_COLOR_DodgerBlue;
extern const SDL_Color SDX_COLOR_Black;

static gpointer _sdx_ui_component_retain0 (gpointer self) {
	return self ? sdx_ui_component_retain (self) : NULL;
}


static Block26Data* block26_data_ref (Block26Data* _data26_) {
	g_atomic_int_inc (&_data26_->_ref_count_);
	return _data26_;
}


static void block26_data_unref (void * _userdata_) {
	Block26Data* _data26_;
	_data26_ = (Block26Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data26_->_ref_count_)) {
		Game* self;
		self = _data26_->self;
		_sdx_ui_component_release0 (_data26_->button);
		_sdx_ui_component_release0 (_data26_->label);
		_entitas_world_release0 (_data26_->world);
		_sdx_ui_component_release0 (_data26_->window);
		_sdx_abstract_game_release0 (self);
		g_slice_free (Block26Data, _data26_);
	}
}


static void __lambda112_ (Block26Data* _data26_) {
	Game* self;
	gfloat _tmp0_;
	self = _data26_->self;
	_tmp0_ = sdx_delta;
	entitas_world_Execute ((EntitasWorld*) _data26_->world, _tmp0_);
}


static void ___lambda112__sdx_abstract_game_abstract_update (gpointer self) {
	__lambda112_ (self);
}


static void __lambda111_ (Block26Data* _data26_, SdxUiComponent* c, gint x, gint y) {
	Game* self;
	SdxUiWindow* _tmp0_;
	SdxUiWindow* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	self = _data26_->self;
	g_return_if_fail (c != NULL);
	_tmp0_ = _data26_->window;
	sdx_ui_component_Remove ((SdxUiComponent*) _tmp0_, (SdxUiComponent*) _data26_->label);
	_tmp1_ = _data26_->window;
	sdx_ui_component_Remove ((SdxUiComponent*) _tmp1_, (SdxUiComponent*) _data26_->button);
	_tmp2_ = x;
	_tmp3_ = y;
	factory_AddPlayer (_data26_->world, _tmp2_, _tmp3_);
	(((SdxAbstractGame*) self)->Update_target_destroy_notify == NULL) ? NULL : (((SdxAbstractGame*) self)->Update_target_destroy_notify (((SdxAbstractGame*) self)->Update_target), NULL);
	((SdxAbstractGame*) self)->Update = NULL;
	((SdxAbstractGame*) self)->Update_target = NULL;
	((SdxAbstractGame*) self)->Update_target_destroy_notify = NULL;
	((SdxAbstractGame*) self)->Update = ___lambda112__sdx_abstract_game_abstract_update;
	((SdxAbstractGame*) self)->Update_target = block26_data_ref (_data26_);
	((SdxAbstractGame*) self)->Update_target_destroy_notify = block26_data_unref;
}


static void ___lambda111__sdx_ui_component_component_on_mouse_click (SdxUiComponent* c, gint x, gint y, gpointer self) {
	__lambda111_ (self, c, x, y);
}


Game* game_new (SdxUiWindow* window) {
	Game* self;
	Block26Data* _data26_;
	SdxUiWindow* _tmp0_;
	SdxUiWindow* _tmp1_;
	SdxUiWindow* _tmp2_;
	SDL_Rect* _tmp3_;
	guint _tmp4_;
	SdxUiWindow* _tmp5_;
	SDL_Rect* _tmp6_;
	guint _tmp7_;
	Factory* _tmp8_;
	SdxUiWindow* _tmp9_;
	const gchar* _tmp10_;
	SdxFont* _tmp11_;
	SDL_Color _tmp12_;
	SdxUiLabelText* _tmp13_;
	SdxFont* _tmp14_;
	SdxUiButtonNinePatch* _tmp15_;
	SdxUiWindow* _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	gint _tmp19_;
	SdxUiComponent* _tmp20_;
	SdxUiComponent* _tmp21_;
	SdxUiWindow* _tmp22_;
	gint _tmp23_;
	gint _tmp24_;
	gint _tmp25_;
	gint _tmp26_;
	SdxUiComponent* _tmp27_;
	SdxUiComponent* _tmp28_;
	SystemsDisplaySystem* display = NULL;
	SystemsDisplaySystem* _tmp29_;
	SystemsSpawnSystem* _tmp30_;
	SystemsSpawnSystem* _tmp31_;
	EntitasWorld* _tmp32_;
	EntitasWorld* _tmp33_;
	SystemsInputSystem* _tmp34_;
	SystemsInputSystem* _tmp35_;
	EntitasWorld* _tmp36_;
	EntitasWorld* _tmp37_;
	SystemsPhysicsSystem* _tmp38_;
	SystemsPhysicsSystem* _tmp39_;
	EntitasWorld* _tmp40_;
	EntitasWorld* _tmp41_;
	SystemsCollisionSystem* _tmp42_;
	SystemsCollisionSystem* _tmp43_;
	EntitasWorld* _tmp44_;
	EntitasWorld* _tmp45_;
	SystemsAnimationSystem* _tmp46_;
	SystemsAnimationSystem* _tmp47_;
	EntitasWorld* _tmp48_;
	EntitasWorld* _tmp49_;
	SystemsExpireSystem* _tmp50_;
	SystemsExpireSystem* _tmp51_;
	EntitasWorld* _tmp52_;
	EntitasWorld* _tmp53_;
	SystemsSoundSystem* _tmp54_;
	SystemsSoundSystem* _tmp55_;
	EntitasWorld* _tmp56_;
	EntitasWorld* _tmp57_;
	SystemsScoreSystem* _tmp58_;
	SystemsScoreSystem* _tmp59_;
	EntitasWorld* _tmp60_;
	EntitasWorld* _tmp61_;
	g_return_val_if_fail (window != NULL, NULL);
	_data26_ = g_slice_new0 (Block26Data);
	_data26_->_ref_count_ = 1;
	_tmp0_ = window;
	_tmp1_ = _sdx_ui_component_retain0 (_tmp0_);
	_sdx_ui_component_release0 (_data26_->window);
	_data26_->window = _tmp1_;
	self = (Game*) sdx_abstract_game_new ();
	_data26_->self = sdx_abstract_game_retain (self);
	_tmp2_ = _data26_->window;
	_tmp3_ = ((SdxUiComponent*) _tmp2_)->bounds;
	_tmp4_ = (*_tmp3_).w;
	((SdxAbstractGame*) self)->width = (gint) _tmp4_;
	_tmp5_ = _data26_->window;
	_tmp6_ = ((SdxUiComponent*) _tmp5_)->bounds;
	_tmp7_ = (*_tmp6_).h;
	((SdxAbstractGame*) self)->height = (gint) _tmp7_;
	sdx_SetResourceBase ("/darkoverlordofdata/shmupwarz");
	sdx_SetSmallFont ("assets/fonts/OpenDyslexic-Bold.otf", 16);
	sdx_SetDefaultFont ("assets/fonts/OpenDyslexic-Bold.otf", 24);
	sdx_SetLargeFont ("assets/fonts/OpenDyslexic-Bold.otf", 36);
	sdx_SetAtlas ("assets/assets.atlas");
	_tmp8_ = factory_new ();
	_data26_->world = _tmp8_;
	_tmp9_ = _data26_->window;
	_tmp10_ = ((SdxUiComponent*) _tmp9_)->name;
	_tmp11_ = sdx_largeFont;
	_tmp12_ = SDX_COLOR_DodgerBlue;
	_tmp13_ = sdx_ui_label_text_new (_tmp10_, _tmp11_, SDX_COLOR_NavajoWhite, &_tmp12_);
	_data26_->label = _tmp13_;
	_tmp14_ = sdx_largeFont;
	_tmp15_ = sdx_ui_button_nine_patch_new ("Start", _tmp14_, SDX_COLOR_Black, "btn", "btnPressed");
	_data26_->button = _tmp15_;
	_tmp16_ = _data26_->window;
	_tmp17_ = ((SdxAbstractGame*) self)->width;
	_tmp18_ = sdx_ui_component_get_width ((SdxUiComponent*) _data26_->label);
	_tmp19_ = _tmp18_;
	_tmp20_ = sdx_ui_component_SetPos ((SdxUiComponent*) _data26_->label, (_tmp17_ / 2) - (_tmp19_ / 2), 10);
	_tmp21_ = _tmp20_;
	sdx_ui_component_Add ((SdxUiComponent*) _tmp16_, _tmp21_);
	_sdx_ui_component_release0 (_tmp21_);
	_tmp22_ = _data26_->window;
	_tmp23_ = ((SdxAbstractGame*) self)->width;
	_tmp24_ = sdx_ui_component_get_width ((SdxUiComponent*) _data26_->button);
	_tmp25_ = _tmp24_;
	_tmp26_ = ((SdxAbstractGame*) self)->height;
	_tmp27_ = sdx_ui_component_SetPos ((SdxUiComponent*) _data26_->button, (_tmp23_ / 2) - (_tmp25_ / 2), _tmp26_ / 3);
	_tmp28_ = _tmp27_;
	sdx_ui_component_Add ((SdxUiComponent*) _tmp22_, _tmp28_);
	_sdx_ui_component_release0 (_tmp28_);
	(((SdxUiComponent*) _data26_->button)->OnMouseClick_target_destroy_notify == NULL) ? NULL : (((SdxUiComponent*) _data26_->button)->OnMouseClick_target_destroy_notify (((SdxUiComponent*) _data26_->button)->OnMouseClick_target), NULL);
	((SdxUiComponent*) _data26_->button)->OnMouseClick = NULL;
	((SdxUiComponent*) _data26_->button)->OnMouseClick_target = NULL;
	((SdxUiComponent*) _data26_->button)->OnMouseClick_target_destroy_notify = NULL;
	((SdxUiComponent*) _data26_->button)->OnMouseClick = ___lambda111__sdx_ui_component_component_on_mouse_click;
	((SdxUiComponent*) _data26_->button)->OnMouseClick_target = block26_data_ref (_data26_);
	((SdxUiComponent*) _data26_->button)->OnMouseClick_target_destroy_notify = block26_data_unref;
	_tmp29_ = systems_display_system_new (self, _data26_->world);
	display = _tmp29_;
	_tmp30_ = systems_spawn_system_new (self, _data26_->world);
	_tmp31_ = _tmp30_;
	_tmp32_ = entitas_world_AddSystem ((EntitasWorld*) _data26_->world, (EntitasSystem*) _tmp31_);
	_tmp33_ = _tmp32_;
	_tmp34_ = systems_input_system_new (self, _data26_->world);
	_tmp35_ = _tmp34_;
	_tmp36_ = entitas_world_AddSystem (_tmp33_, (EntitasSystem*) _tmp35_);
	_tmp37_ = _tmp36_;
	_tmp38_ = systems_physics_system_new (self, _data26_->world);
	_tmp39_ = _tmp38_;
	_tmp40_ = entitas_world_AddSystem (_tmp37_, (EntitasSystem*) _tmp39_);
	_tmp41_ = _tmp40_;
	_tmp42_ = systems_collision_system_new (self, _data26_->world);
	_tmp43_ = _tmp42_;
	_tmp44_ = entitas_world_AddSystem (_tmp41_, (EntitasSystem*) _tmp43_);
	_tmp45_ = _tmp44_;
	_tmp46_ = systems_animation_system_new (self, _data26_->world);
	_tmp47_ = _tmp46_;
	_tmp48_ = entitas_world_AddSystem (_tmp45_, (EntitasSystem*) _tmp47_);
	_tmp49_ = _tmp48_;
	_tmp50_ = systems_expire_system_new (self, _data26_->world);
	_tmp51_ = _tmp50_;
	_tmp52_ = entitas_world_AddSystem (_tmp49_, (EntitasSystem*) _tmp51_);
	_tmp53_ = _tmp52_;
	_tmp54_ = systems_sound_system_new (self, _data26_->world);
	_tmp55_ = _tmp54_;
	_tmp56_ = entitas_world_AddSystem (_tmp53_, (EntitasSystem*) _tmp55_);
	_tmp57_ = _tmp56_;
	_tmp58_ = systems_score_system_new (self, _data26_->world);
	_tmp59_ = _tmp58_;
	_tmp60_ = entitas_world_AddSystem (_tmp57_, (EntitasSystem*) _tmp59_);
	_tmp61_ = _tmp60_;
	_entitas_world_release0 (_tmp61_);
	_entitas_system_release0 (_tmp59_);
	_entitas_world_release0 (_tmp57_);
	_entitas_system_release0 (_tmp55_);
	_entitas_world_release0 (_tmp53_);
	_entitas_system_release0 (_tmp51_);
	_entitas_world_release0 (_tmp49_);
	_entitas_system_release0 (_tmp47_);
	_entitas_world_release0 (_tmp45_);
	_entitas_system_release0 (_tmp43_);
	_entitas_world_release0 (_tmp41_);
	_entitas_system_release0 (_tmp39_);
	_entitas_world_release0 (_tmp37_);
	_entitas_system_release0 (_tmp35_);
	_entitas_world_release0 (_tmp33_);
	_entitas_system_release0 (_tmp31_);
	entitas_world_Initialize ((EntitasWorld*) _data26_->world);
	factory_AddBackground (_data26_->world, 0, 0);
	_systems_display_system_release0 (display);
	block26_data_unref (_data26_);
	_data26_ = NULL;
	return self;
}




