/** updated by adriac */
/* ApplicationListener.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from ApplicationListener.vala, do not modify */

/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>


#define SDX_TYPE_APPLICATION_LISTENER (sdx_application_listener_get_type ())
typedef struct _SdxApplicationListener SdxApplicationListener;

typedef void (*SdxApplicationListenerCreate) (void* user_data);
typedef void (*SdxApplicationListenerResize) (gint width, gint height, void* user_data);
typedef void (*SdxApplicationListenerRender) (void* user_data);
typedef void (*SdxApplicationListenerPause) (void* user_data);
typedef void (*SdxApplicationListenerResume) (void* user_data);
typedef void (*SdxApplicationListenerDispose) (void* user_data);
struct _SdxApplicationListener {
	SdxApplicationListenerCreate Create;
	gpointer Create_target;
	GDestroyNotify Create_target_destroy_notify;
	SdxApplicationListenerResize Resize;
	gpointer Resize_target;
	GDestroyNotify Resize_target_destroy_notify;
	SdxApplicationListenerRender Render;
	gpointer Render_target;
	GDestroyNotify Render_target_destroy_notify;
	SdxApplicationListenerPause Pause;
	gpointer Pause_target;
	GDestroyNotify Pause_target_destroy_notify;
	SdxApplicationListenerResume Resume;
	gpointer Resume_target;
	GDestroyNotify Resume_target_destroy_notify;
	SdxApplicationListenerDispose Dispose;
	gpointer Dispose_target;
	GDestroyNotify Dispose_target_destroy_notify;
};



GType sdx_application_listener_get_type (void) G_GNUC_CONST;
SdxApplicationListener* sdx_application_listener_dup (const SdxApplicationListener* self);
void sdx_application_listener_free (SdxApplicationListener* self);
void sdx_application_listener_copy (const SdxApplicationListener* self, SdxApplicationListener* dest);
void sdx_application_listener_destroy (SdxApplicationListener* self);


void sdx_application_listener_copy (const SdxApplicationListener* self, SdxApplicationListener* dest) {
	SdxApplicationListenerCreate _tmp0_;
	void* _tmp0__target;
	SdxApplicationListenerResize _tmp1_;
	void* _tmp1__target;
	SdxApplicationListenerRender _tmp2_;
	void* _tmp2__target;
	SdxApplicationListenerPause _tmp3_;
	void* _tmp3__target;
	SdxApplicationListenerResume _tmp4_;
	void* _tmp4__target;
	SdxApplicationListenerDispose _tmp5_;
	void* _tmp5__target;
	_tmp0_ = (*self).Create;
	_tmp0__target = (*self).Create_target;
	((*dest).Create_target_destroy_notify == NULL) ? NULL : ((*dest).Create_target_destroy_notify ((*dest).Create_target), NULL);
	(*dest).Create = NULL;
	(*dest).Create_target = NULL;
	(*dest).Create_target_destroy_notify = NULL;
	(*dest).Create = _tmp0_;
	(*dest).Create_target = _tmp0__target;
	(*dest).Create_target_destroy_notify = NULL;
	_tmp1_ = (*self).Resize;
	_tmp1__target = (*self).Resize_target;
	((*dest).Resize_target_destroy_notify == NULL) ? NULL : ((*dest).Resize_target_destroy_notify ((*dest).Resize_target), NULL);
	(*dest).Resize = NULL;
	(*dest).Resize_target = NULL;
	(*dest).Resize_target_destroy_notify = NULL;
	(*dest).Resize = _tmp1_;
	(*dest).Resize_target = _tmp1__target;
	(*dest).Resize_target_destroy_notify = NULL;
	_tmp2_ = (*self).Render;
	_tmp2__target = (*self).Render_target;
	((*dest).Render_target_destroy_notify == NULL) ? NULL : ((*dest).Render_target_destroy_notify ((*dest).Render_target), NULL);
	(*dest).Render = NULL;
	(*dest).Render_target = NULL;
	(*dest).Render_target_destroy_notify = NULL;
	(*dest).Render = _tmp2_;
	(*dest).Render_target = _tmp2__target;
	(*dest).Render_target_destroy_notify = NULL;
	_tmp3_ = (*self).Pause;
	_tmp3__target = (*self).Pause_target;
	((*dest).Pause_target_destroy_notify == NULL) ? NULL : ((*dest).Pause_target_destroy_notify ((*dest).Pause_target), NULL);
	(*dest).Pause = NULL;
	(*dest).Pause_target = NULL;
	(*dest).Pause_target_destroy_notify = NULL;
	(*dest).Pause = _tmp3_;
	(*dest).Pause_target = _tmp3__target;
	(*dest).Pause_target_destroy_notify = NULL;
	_tmp4_ = (*self).Resume;
	_tmp4__target = (*self).Resume_target;
	((*dest).Resume_target_destroy_notify == NULL) ? NULL : ((*dest).Resume_target_destroy_notify ((*dest).Resume_target), NULL);
	(*dest).Resume = NULL;
	(*dest).Resume_target = NULL;
	(*dest).Resume_target_destroy_notify = NULL;
	(*dest).Resume = _tmp4_;
	(*dest).Resume_target = _tmp4__target;
	(*dest).Resume_target_destroy_notify = NULL;
	_tmp5_ = (*self).Dispose;
	_tmp5__target = (*self).Dispose_target;
	((*dest).Dispose_target_destroy_notify == NULL) ? NULL : ((*dest).Dispose_target_destroy_notify ((*dest).Dispose_target), NULL);
	(*dest).Dispose = NULL;
	(*dest).Dispose_target = NULL;
	(*dest).Dispose_target_destroy_notify = NULL;
	(*dest).Dispose = _tmp5_;
	(*dest).Dispose_target = _tmp5__target;
	(*dest).Dispose_target_destroy_notify = NULL;
}


void sdx_application_listener_destroy (SdxApplicationListener* self) {
	((*self).Create_target_destroy_notify == NULL) ? NULL : ((*self).Create_target_destroy_notify ((*self).Create_target), NULL);
	(*self).Create = NULL;
	(*self).Create_target = NULL;
	(*self).Create_target_destroy_notify = NULL;
	((*self).Resize_target_destroy_notify == NULL) ? NULL : ((*self).Resize_target_destroy_notify ((*self).Resize_target), NULL);
	(*self).Resize = NULL;
	(*self).Resize_target = NULL;
	(*self).Resize_target_destroy_notify = NULL;
	((*self).Render_target_destroy_notify == NULL) ? NULL : ((*self).Render_target_destroy_notify ((*self).Render_target), NULL);
	(*self).Render = NULL;
	(*self).Render_target = NULL;
	(*self).Render_target_destroy_notify = NULL;
	((*self).Pause_target_destroy_notify == NULL) ? NULL : ((*self).Pause_target_destroy_notify ((*self).Pause_target), NULL);
	(*self).Pause = NULL;
	(*self).Pause_target = NULL;
	(*self).Pause_target_destroy_notify = NULL;
	((*self).Resume_target_destroy_notify == NULL) ? NULL : ((*self).Resume_target_destroy_notify ((*self).Resume_target), NULL);
	(*self).Resume = NULL;
	(*self).Resume_target = NULL;
	(*self).Resume_target_destroy_notify = NULL;
	((*self).Dispose_target_destroy_notify == NULL) ? NULL : ((*self).Dispose_target_destroy_notify ((*self).Dispose_target), NULL);
	(*self).Dispose = NULL;
	(*self).Dispose_target = NULL;
	(*self).Dispose_target_destroy_notify = NULL;
}


SdxApplicationListener* sdx_application_listener_dup (const SdxApplicationListener* self) {
	SdxApplicationListener* dup;
	dup = g_new0 (SdxApplicationListener, 1);
	sdx_application_listener_copy (self, dup);
	return dup;
}


void sdx_application_listener_free (SdxApplicationListener* self) {
	sdx_application_listener_destroy (self);
	g_free (self);
}


GType sdx_application_listener_get_type (void) {
	static volatile gsize sdx_application_listener_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_application_listener_type_id__volatile)) {
		GType sdx_application_listener_type_id;
		sdx_application_listener_type_id = g_boxed_type_register_static ("SdxApplicationListener", (GBoxedCopyFunc) sdx_application_listener_dup, (GBoxedFreeFunc) sdx_application_listener_free);
		g_once_init_leave (&sdx_application_listener_type_id__volatile, sdx_application_listener_type_id);
	}
	return sdx_application_listener_type_id__volatile;
}




