/** updated by adriac */
/* exceptions.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from exceptions.vala, do not modify */

/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>


typedef enum  {
	SDX_IO_EXCEPTION_InvalidData
} SdxIOException;
#define SDX_IO_EXCEPTION sdx_io_exception_quark ()
typedef enum  {
	SDX_EXCEPTION_IllegalArgumentException,
	SDX_EXCEPTION_RuntimeException
} SdxException;
#define SDX_EXCEPTION sdx_exception_quark ()
typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer,
	SDX_SDL_EXCEPTION_InvalidForPlatform,
	SDX_SDL_EXCEPTION_UnableToLoadResource,
	SDX_SDL_EXCEPTION_UnableToLoadSurface,
	SDX_SDL_EXCEPTION_UnableToLoadTexture,
	SDX_SDL_EXCEPTION_NullPointer,
	SDX_SDL_EXCEPTION_NoSuchElement,
	SDX_SDL_EXCEPTION_IllegalStateException,
	SDX_SDL_EXCEPTION_IllegalArgumentException,
	SDX_SDL_EXCEPTION_RuntimeException,
	SDX_SDL_EXCEPTION_NotReached
} SdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()


GQuark sdx_io_exception_quark (void);
GQuark sdx_exception_quark (void);
GQuark sdx_sdl_exception_quark (void);


GQuark sdx_io_exception_quark (void) {
	return g_quark_from_static_string ("sdx_io_exception-quark");
}


GQuark sdx_exception_quark (void) {
	return g_quark_from_static_string ("sdx_exception-quark");
}


GQuark sdx_sdl_exception_quark (void) {
	return g_quark_from_static_string ("sdx_sdl_exception-quark");
}




