/** updated by adriac */
/* SpawnSystem.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from SpawnSystem.vala, do not modify */

/*[Adriac:Systems::SpawnSystem:SystemsSpawnSystem:systems_spawn_system]*/

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>

typedef struct _EntitasSystem EntitasSystem;
typedef EntitasSystem SystemsSpawnSystem;
typedef struct _SdxAbstractGame SdxAbstractGame;
typedef SdxAbstractGame Game;
typedef struct _EntitasWorld EntitasWorld;
typedef EntitasWorld Factory;
// symtbl.1 sdx_abstract_game
void sdx_abstract_game_release (SdxAbstractGame* self);
void sdx_abstract_game_free (SdxAbstractGame* self);
SdxAbstractGame* sdx_abstract_game_retain (SdxAbstractGame* self);
#define _sdx_abstract_game_release0(var) ((var == NULL) ? NULL : (var = (sdx_abstract_game_release (var), NULL)))
// symtbl.1 entitas_world
void entitas_world_release (EntitasWorld* self);
void entitas_world_free (EntitasWorld* self);
EntitasWorld* entitas_world_retain (EntitasWorld* self);
#define _entitas_world_release0(var) ((var == NULL) ? NULL : (var = (entitas_world_release (var), NULL)))
typedef struct _Block39Data Block39Data;
// symtbl.1 entitas_system
void entitas_system_release (EntitasSystem* self);
void entitas_system_free (EntitasSystem* self);
EntitasSystem* entitas_system_retain (EntitasSystem* self);
#define _entitas_system_release0(var) ((var == NULL) ? NULL : (var = (entitas_system_release (var), NULL)))

typedef void (*EntitasSystemInitialize) (void* user_data);
typedef void (*EntitasSystemExecute) (gfloat delta, void* user_data);
struct _EntitasSystem {
	gint ref_count;
	EntitasSystemInitialize Initialize;
	gpointer Initialize_target;
	GDestroyNotify Initialize_target_destroy_notify;
	EntitasSystemExecute Execute;
	gpointer Execute_target;
	GDestroyNotify Execute_target_destroy_notify;
};

typedef gfloat (*SystemsSpawnSystemSpawnEnemyFunc) (gfloat delta, gfloat t, gint enemy, void* user_data);
struct _Block39Data {
	int _ref_count_;
	SystemsSpawnSystem* self;
	gfloat enemyT1;
	gfloat enemyT2;
	gfloat enemyT3;
	SystemsSpawnSystemSpawnEnemyFunc SpawnEnemy;
	gpointer SpawnEnemy_target;
	GDestroyNotify SpawnEnemy_target_destroy_notify;
	Game* game;
	Factory* world;
};

typedef void (*SdxAbstractGameAbstractUpdate) (void* user_data);
typedef void (*SdxAbstractGameAbstractDraw) (void* user_data);
struct _SdxAbstractGame {
	gint ref_count;
	gint width;
	gint height;
	SdxAbstractGameAbstractUpdate Update;
	gpointer Update_target;
	GDestroyNotify Update_target_destroy_notify;
	SdxAbstractGameAbstractDraw Draw;
	gpointer Draw_target;
	GDestroyNotify Draw_target_destroy_notify;
};



void entitas_system_free (EntitasSystem * self);
void sdx_abstract_game_free (SdxAbstractGame * self);
void entitas_world_free (EntitasWorld * self);
SystemsSpawnSystem* systems_spawn_system_new (Game* game, Factory* world);
static Block39Data* block39_data_ref (Block39Data* _data39_);
static void block39_data_unref (void * _userdata_);
EntitasSystem* entitas_system_new (void);
static gfloat __lambda117_ (Block39Data* _data39_, gfloat delta, gfloat t, gint enemy);
gdouble sdx_GetRandom (void);
void factory_AddEnemy1 (Factory* self, gint x, gint y);
void factory_AddEnemy2 (Factory* self, gint x, gint y);
void factory_AddEnemy3 (Factory* self, gint x, gint y);
static gfloat ___lambda117__systems_spawn_system_spawn_enemy_func (gfloat delta, gfloat t, gint enemy, gpointer self);
static void __lambda118_ (Block39Data* _data39_, gfloat delta);
static void ___lambda118__entitas_system_execute (gfloat delta, gpointer self);


static gpointer _sdx_abstract_game_retain0 (gpointer self) {
	return self ? sdx_abstract_game_retain (self) : NULL;
}


static gpointer _entitas_world_retain0 (gpointer self) {
	return self ? entitas_world_retain (self) : NULL;
}


static Block39Data* block39_data_ref (Block39Data* _data39_) {
	g_atomic_int_inc (&_data39_->_ref_count_);
	return _data39_;
}


static void block39_data_unref (void * _userdata_) {
	Block39Data* _data39_;
	_data39_ = (Block39Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data39_->_ref_count_)) {
		SystemsSpawnSystem* self;
		self = _data39_->self;
		(_data39_->SpawnEnemy_target_destroy_notify == NULL) ? NULL : (_data39_->SpawnEnemy_target_destroy_notify (_data39_->SpawnEnemy_target), NULL);
		_data39_->SpawnEnemy = NULL;
		_data39_->SpawnEnemy_target = NULL;
		_data39_->SpawnEnemy_target_destroy_notify = NULL;
		_sdx_abstract_game_release0 (_data39_->game);
		_entitas_world_release0 (_data39_->world);
		_entitas_system_release0 (self);
		g_slice_free (Block39Data, _data39_);
	}
}


static gfloat __lambda117_ (Block39Data* _data39_, gfloat delta, gfloat t, gint enemy) {
	SystemsSpawnSystem* self;
	gfloat result = 0.0F;
	gfloat d1 = 0.0F;
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	self = _data39_->self;
	_tmp0_ = t;
	_tmp1_ = delta;
	d1 = _tmp0_ - _tmp1_;
	_tmp2_ = d1;
	if (((gdouble) _tmp2_) < 0.0) {
		gint _tmp3_;
		_tmp3_ = enemy;
		switch (_tmp3_) {
			case 1:
			{
				gint x = 0;
				gdouble _tmp4_;
				Game* _tmp5_;
				gint _tmp6_;
				Factory* _tmp7_;
				gint _tmp8_;
				_tmp4_ = sdx_GetRandom ();
				_tmp5_ = _data39_->game;
				_tmp6_ = ((SdxAbstractGame*) _tmp5_)->width;
				x = ((gint) (_tmp4_ * (_tmp6_ - 70))) + 35;
				_tmp7_ = _data39_->world;
				_tmp8_ = x;
				factory_AddEnemy1 (_tmp7_, _tmp8_, -35);
				result = (gfloat) 1;
				return result;
			}
			case 2:
			{
				gint x = 0;
				gdouble _tmp9_;
				Game* _tmp10_;
				gint _tmp11_;
				Factory* _tmp12_;
				gint _tmp13_;
				_tmp9_ = sdx_GetRandom ();
				_tmp10_ = _data39_->game;
				_tmp11_ = ((SdxAbstractGame*) _tmp10_)->width;
				x = ((gint) (_tmp9_ * (_tmp11_ - 172))) + 85;
				_tmp12_ = _data39_->world;
				_tmp13_ = x;
				factory_AddEnemy2 (_tmp12_, _tmp13_, -85);
				result = (gfloat) 4;
				return result;
			}
			case 3:
			{
				gint x = 0;
				gdouble _tmp14_;
				Game* _tmp15_;
				gint _tmp16_;
				Factory* _tmp17_;
				gint _tmp18_;
				_tmp14_ = sdx_GetRandom ();
				_tmp15_ = _data39_->game;
				_tmp16_ = ((SdxAbstractGame*) _tmp15_)->width;
				x = ((gint) (_tmp14_ * (_tmp16_ - 320))) + 160;
				_tmp17_ = _data39_->world;
				_tmp18_ = x;
				factory_AddEnemy3 (_tmp17_, _tmp18_, -160);
				result = (gfloat) 6;
				return result;
			}
			default:
			{
				result = (gfloat) 0;
				return result;
			}
		}
	} else {
		result = d1;
		return result;
	}
}


static gfloat ___lambda117__systems_spawn_system_spawn_enemy_func (gfloat delta, gfloat t, gint enemy, gpointer self) {
	gfloat result;
	result = __lambda117_ (self, delta, t, enemy);
	return result;
}


static void __lambda118_ (Block39Data* _data39_, gfloat delta) {
	SystemsSpawnSystem* self;
	gfloat _tmp0_;
	gfloat _tmp1_;
	gfloat _tmp2_;
	gfloat _tmp3_;
	gfloat _tmp4_;
	gfloat _tmp5_;
	self = _data39_->self;
	_tmp0_ = delta;
	_tmp1_ = _data39_->SpawnEnemy (_tmp0_, _data39_->enemyT1, 1, _data39_->SpawnEnemy_target);
	_data39_->enemyT1 = _tmp1_;
	_tmp2_ = delta;
	_tmp3_ = _data39_->SpawnEnemy (_tmp2_, _data39_->enemyT2, 2, _data39_->SpawnEnemy_target);
	_data39_->enemyT2 = _tmp3_;
	_tmp4_ = delta;
	_tmp5_ = _data39_->SpawnEnemy (_tmp4_, _data39_->enemyT3, 3, _data39_->SpawnEnemy_target);
	_data39_->enemyT3 = _tmp5_;
}


static void ___lambda118__entitas_system_execute (gfloat delta, gpointer self) {
	__lambda118_ (self, delta);
}


SystemsSpawnSystem* systems_spawn_system_new (Game* game, Factory* world) {
	SystemsSpawnSystem* self;
	Block39Data* _data39_;
	Game* _tmp0_;
	Game* _tmp1_;
	Factory* _tmp2_;
	Factory* _tmp3_;
	g_return_val_if_fail (game != NULL, NULL);
	g_return_val_if_fail (world != NULL, NULL);
	_data39_ = g_slice_new0 (Block39Data);
	_data39_->_ref_count_ = 1;
	_tmp0_ = game;
	_tmp1_ = _sdx_abstract_game_retain0 (_tmp0_);
	_sdx_abstract_game_release0 (_data39_->game);
	_data39_->game = _tmp1_;
	_tmp2_ = world;
	_tmp3_ = _entitas_world_retain0 (_tmp2_);
	_entitas_world_release0 (_data39_->world);
	_data39_->world = _tmp3_;
	self = (SystemsSpawnSystem*) entitas_system_new ();
	_data39_->self = entitas_system_retain (self);
	_data39_->enemyT1 = 1.0f;
	_data39_->enemyT2 = 4.0f;
	_data39_->enemyT3 = 6.0f;
	_data39_->SpawnEnemy = ___lambda117__systems_spawn_system_spawn_enemy_func;
	_data39_->SpawnEnemy_target = block39_data_ref (_data39_);
	_data39_->SpawnEnemy_target_destroy_notify = block39_data_unref;
	(((EntitasSystem*) self)->Execute_target_destroy_notify == NULL) ? NULL : (((EntitasSystem*) self)->Execute_target_destroy_notify (((EntitasSystem*) self)->Execute_target), NULL);
	((EntitasSystem*) self)->Execute = NULL;
	((EntitasSystem*) self)->Execute_target = NULL;
	((EntitasSystem*) self)->Execute_target_destroy_notify = NULL;
	((EntitasSystem*) self)->Execute = ___lambda118__entitas_system_execute;
	((EntitasSystem*) self)->Execute_target = block39_data_ref (_data39_);
	((EntitasSystem*) self)->Execute_target_destroy_notify = block39_data_unref;
	block39_data_unref (_data39_);
	_data39_ = NULL;
	return self;
}




