/** updated by adriac */
/* files.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from files.vala, do not modify */

/* ******************************************************************************
 * Copyright 2017 darkoverlordofdata.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SDX_TYPE_FILE_TYPE (sdx_file_type_get_type ())
typedef struct _SdxFilesFileHandle SdxFilesFileHandle;

typedef enum  {
	SDX_FILE_TYPE_Resource = 1,
	SDX_FILE_TYPE_Asset,
	SDX_FILE_TYPE_Absolute,
	SDX_FILE_TYPE_Relative
} SdxFileType;



GType sdx_file_type_get_type (void) G_GNUC_CONST;
void sdx_files_file_handle_free (SdxFilesFileHandle * self);
SdxFilesFileHandle* sdx_files_GetHandle (const gchar* path, SdxFileType type);
SdxFilesFileHandle* sdx_files_file_handle_new (const gchar* path, SdxFileType type);
SdxFilesFileHandle* sdx_files_Resource (const gchar* path);
SdxFilesFileHandle* sdx_files_Asset (const gchar* path);
SdxFilesFileHandle* sdx_files_Absolute (const gchar* path);
SdxFilesFileHandle* sdx_files_Relative (const gchar* path);
SdxFilesFileHandle* sdx_files_Default (const gchar* path);


SdxFilesFileHandle* sdx_files_GetHandle (const gchar* path, SdxFileType type) {
	SdxFilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	SdxFileType _tmp1_;
	SdxFilesFileHandle* _tmp2_;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = type;
	_tmp2_ = sdx_files_file_handle_new (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


SdxFilesFileHandle* sdx_files_Resource (const gchar* path) {
	SdxFilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	SdxFilesFileHandle* _tmp1_;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Resource);
	result = _tmp1_;
	return result;
}


SdxFilesFileHandle* sdx_files_Asset (const gchar* path) {
	SdxFilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	SdxFilesFileHandle* _tmp1_;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Asset);
	result = _tmp1_;
	return result;
}


SdxFilesFileHandle* sdx_files_Absolute (const gchar* path) {
	SdxFilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	SdxFilesFileHandle* _tmp1_;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Absolute);
	result = _tmp1_;
	return result;
}


SdxFilesFileHandle* sdx_files_Relative (const gchar* path) {
	SdxFilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	SdxFilesFileHandle* _tmp1_;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Relative);
	result = _tmp1_;
	return result;
}


SdxFilesFileHandle* sdx_files_Default (const gchar* path) {
	SdxFilesFileHandle* result = NULL;
	const gchar* _tmp0_;
	SdxFilesFileHandle* _tmp1_;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = path;
	_tmp1_ = sdx_files_file_handle_new (_tmp0_, SDX_FILE_TYPE_Relative);
	result = _tmp1_;
	return result;
}




